(() => {
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=(src,alt,cls='')=>src?`<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" onerror="this.hidden=true">`:'';
const crest=(id,name,cls='')=>img(`crests/${id}.webp`,name,cls),flag=p=>p.nationId?img(`icons/countries/${p.nationId}.webp`,p.nationName||p.country,'tiny-flag'):'';
const val=v=>typeof v==='number'&&v>=0?v:'—';
let ctx={},active='home',competitionId=null,modal=null,modalMode='xi',pose=1,modalRevision=0,onChange=()=>{},coachCanvas=null;
let newsElapsed=0,newsLastTick=performance.now();const NEWS_DURATION=12000;
const slides={},clubs=new Map(),loading=new Set();
const d=()=>ctx.detail||{},players=()=>d().players||[],web=()=>d().webDashboard||{};
const rate=s=>s&&s.recorded!==false&&[s.games,s.wins,s.draws].every(v=>typeof v==='number'&&v>=0)?(s.games?(3*s.wins+s.draws)/(3*s.games)*100:0):null;
function ring(value,label){const n=typeof value==='number'&&value>=0?Math.min(100,value):null;return `<div class="dash-ring-block"><div class="dash-ring" style="--progress:${n??0}%" role="img" aria-label="${esc(label)} ${n==null?'não informado':Math.round(n)+' por cento'}"><strong>${n==null?'—':Math.round(n)+'%'}</strong></div><small>${esc(label)}</small></div>`;}
function nav(key,count){const current=(slides[key]||0)%Math.max(1,count);return `<div class="dash-carousel-controls"><button class="circle" data-dashboard-action="slide:${key}:-1" aria-label="Anterior: ${key}">‹</button><div class="dash-dots">${Array.from({length:count},(_,i)=>`<button aria-label="Página ${i+1}: ${key}" aria-current="${i===current}" data-dashboard-action="goto:${key}:${i}" class="${i===current?'active':''}"></button>`).join('')}</div><button class="circle" data-dashboard-action="slide:${key}:1" aria-label="Próximo: ${key}">›</button></div>`;}
function panel(key,title,html,count=1,cls=''){return `<section class="panel dash-card ${cls}" data-dashboard-panel="${key}"><div class="dash-card-heading"><h2>${esc(title)}</h2></div><div class="dash-card-content">${html}</div>${count>1?nav(key,count):''}</section>`;}
function match(){return d().nextMatch||web().upcoming?.[0]||null;}
function kit(side){const club=clubs.get(side)|| (Number(side)===Number(ctx.clubId)?d():null);return club?.kits?.find(k=>k.name==='Mandante')?.image;}
function nextMatch(){const m=match();if(!m)return `<section class="panel dash-card match-card" data-dashboard-panel="match"><h2>Próxima partida</h2><div class="dash-empty">A agenda da carreira ainda não informa o próximo jogo.</div></section>`;
const home=clubs.get(m.home)||(m.home===ctx.clubId?d():null),away=clubs.get(m.away)||(m.away===ctx.clubId?d():null),stadium=home?.stadium;
return `<section class="panel dash-card match-card" data-dashboard-panel="match"><h2>Próxima partida</h2><div class="match-competition">${img(m.asset?`icons/leagues/${m.asset}.webp`:'','')}${esc(m.competition||'Competição da carreira')}</div><div class="match-teams">${[m.home,m.away].map((id,i)=>`<div>${crest(id,i?m.awayName:m.homeName)}${img(kit(id),'Uniforme','match-kit')}<strong>${esc(i?m.awayName:m.homeName)}</strong><small>${esc((i?away:home)?.coach?.name||'Técnico não informado')}</small></div>${i===0?'<b class="match-versus">×</b>':''}`).join('')}</div><div class="match-info"><span>Data <b>${esc(typeof m.date==='number'?String(m.date).slice(6,8)+'/'+String(m.date).slice(4,6):m.date||'—')}</b></span><span>Hora <b>${esc(m.time||'—')}</b></span></div><div class="match-venue">${img(stadium?.image,'Estádio')}<div><strong>${esc(m.stadium||stadium?.name||'Estádio não informado')}</strong><small>Capacidade <b>${typeof m.capacity==='number'&&m.capacity>0?m.capacity.toLocaleString('pt-BR'):typeof stadium?.capacity==='number'?stadium.capacity.toLocaleString('pt-BR'):'—'}</b></small><small>Público estimado <b>${val(m.attendance)}${typeof m.attendance==='number'&&m.attendance>=0?'%':''}</b></small></div></div></section>`;}
function newsItems(){return [{title:`${ctx.clubName||'Seu clube'}: seu time em campo`,subtitle:d().formation?`Conheça o elenco e acompanhe sua carreira. A equipe está organizada no ${d().formation}.`:'Conheça os jogadores e acompanhe os próximos capítulos da sua carreira.',art:'lineup',category:'Elenco'},...(window.FF_CAREER_NEWS_DEMO||[]),...(d().news||[])];}
function news(){const list=newsItems(),index=(slides.news||0)%list.length,n=list[index],c=d().coach||{},p=players()[0]||{},source=n.image||(n.art==='coach'?(c.photo||c.portrait||c.model):n.art==='player'?p.portrait:n.art==='stadium'?d().stadium?.image:n.art==='training'?d().rooms?.training:n.art==='locker'?d().rooms?.locker:d().lineupScene);return `<section class="panel dash-card news-card span-two" data-dashboard-panel="news" data-nav-item tabindex="0" aria-label="Notícias da carreira. ${esc(n.title)}" aria-roledescription="carrossel"><div class="eyebrow">Notícias da carreira</div><div class="news-body"><div class="news-copy" aria-live="polite"><h2>${esc(n.title)}</h2><p>${esc(n.subtitle||'')}</p><small>${esc(n.category||'Carreira')} · ${esc(ctx.clubName)}${index>0&&index<=(window.FF_CAREER_NEWS_DEMO||[]).length?' · Prévia':''}</small></div><div class="news-art news-art-${esc(n.art||'image')}">${crest(ctx.clubId,ctx.clubName,'news-crest')}${img(source,n.art==='coach'?c.name:'Seu clube','news-visual')}</div></div><div class="news-progress" role="progressbar" aria-label="Tempo até a próxima notícia" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">${list.map((_,i)=>`<span class="${i===index?'active':''}" data-news-index="${i}"><i class="news-dot-fill"></i></span>`).join('')}</div></section>`;}
function bindNews(){const card=document.querySelector('[data-dashboard-panel="news"]');if(!card||card.dataset.newsBound)return;card.dataset.newsBound='true';card.addEventListener('click',event=>{const mark=event.target.closest('[data-news-index]');handle(mark?'goto:news:'+mark.dataset.newsIndex:'slide:news:1');});card.addEventListener('wheel',event=>{event.preventDefault();if(Date.now()<(card._wheelAt||0))return;card._wheelAt=Date.now()+450;handle('slide:news:'+((event.deltaX||event.deltaY)>0?1:-1));},{passive:false});}
function coach(){const c=d().coach||{},confidence=d().boardConfidence??c.confidence;return `<button class="panel dash-card staff-card" data-action="coach"><div class="eyebrow">Comissão técnica</div><div class="staff-portrait">${c.photo||c.model?img(c.photoKind==='game-model-render'?c.photo:c.model||c.photo,c.name,'staff-fallback'):'<div class="card-loading">Preparando treinador…</div>'}<canvas data-coach-3d data-readonly="true" data-framing="face" hidden aria-label="Modelo 3D do treinador"></canvas></div><h2>${esc(c.name||'Treinador')}</h2><div class="staff-nationality">${flag(c)}${esc(c.country||'Nacionalidade não informada')}</div><p class="staff-league">${esc(c.league||'Liga não informada')}</p><div class="staff-metrics">${ring(rate(d().season),'Aproveitamento geral')}${ring(confidence,'Prestígio da diretoria')}</div></button>`;}
function leaderRows(rows,unit=''){return rows?.length?`<div class="dash-leaders">${rows.slice(0,5).map((r,i)=>`<button data-player="${esc(r.player||r.id)}" data-player-club="${r.club||ctx.clubId}" class="dash-leader"><span class="leader-rank">${i+1}</span>${img(r.portrait||`assets/players/${r.player||r.id}.webp`,r.name,'leader-head')}<strong>${esc(r.name)}</strong><b>${val(r.value??r.overall)}<small>${esc(unit)}</small></b>${crest(r.club||ctx.clubId,'Clube','leader-crest')}</button>`).join('')}</div>`:'<div class="dash-empty">Sem estatísticas registradas.</div>';}
function selectedCompetition(){const list=web().competitions?.length?web().competitions:(d().competitions||[]);return list.find(e=>String(e.root)===String(competitionId))||list.find(e=>e.root===web().current)||list[0]||null;}
function competitionTable(){const c=selectedCompetition(),rows=c?.table||[];return `<section class="panel dash-card span-two standings-card"><div class="competition-heading">${img(c?.asset?`icons/leagues/${c.asset}.webp`:'','Competição')}<h2>${esc(c?.name||'Competição atual')}</h2></div><div class="competition-tabs">${(web().competitions?.length?web().competitions:d().competitions||[]).map(e=>`<button class="${e===c?'active':''}" data-dashboard-action="competition:${e.root}">${esc(e.name)}</button>`).join('')}</div><div class="standings-scroll"><table class="dash-table"><thead><tr><th>#</th><th>Clube</th>${['J','V','E','D','GP','GC','SG','PTS'].map(k=>`<th>${k}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr class="${Number(r.team)===Number(ctx.clubId)?'my-club':''}"><td>${val(r.rank)}</td><th>${crest(r.team,r.name)}${esc(r.name)}</th>${[r.games,r.wins,r.draws,r.losses,r.goalsFor,r.goalsAgainst,typeof r.goalsFor==='number'&&typeof r.goalsAgainst==='number'?r.goalsFor-r.goalsAgainst:null,r.points].map(v=>`<td>${v==null?'—':esc(v)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="10">Classificação ainda não disponível nesta fonte da carreira.</td></tr>'}</tbody></table></div></section>`;}
function fixtures(rows){return rows?.length?`<div class="dash-fixtures">${rows.slice(0,10).map(m=>`<div><span>${esc(typeof m.date==='number'?String(m.date).slice(6,8)+'/'+String(m.date).slice(4,6):m.date||'—')}<small>${esc(m.time||'')}</small></span>${img(m.asset?`icons/leagues/${m.asset}.webp`:'',m.competition,'fixture-comp')}${crest(m.home,m.homeName)}<b>${esc(m.score||'×')}</b>${crest(m.away,m.awayName)}<small class="fixture-names">${esc(m.homeName)} × ${esc(m.awayName)}</small></div>`).join('')}</div>`:'<div class="dash-empty">Nenhuma partida informada nesta fonte da carreira.</div>';}
function status(){const c=selectedCompetition(),row=c?.table?.find(r=>Number(r.team)===Number(ctx.clubId));return `<div class="club-status">${crest(ctx.clubId,ctx.clubName)}<h3>${esc(ctx.clubName)}</h3><strong>${row?val(row.rank)+'º':'—'}</strong><small>Colocação · ${esc(c?.name||'Competição')}</small>${ring(row?rate(row):rate(d().season),'Aproveitamento')}<div class="status-numbers"><span>${val(row?.points)}<small>Pontos</small></span><span>${val(row?.games)}<small>Jogos</small></span></div></div>`;}
function schedule(){const key='schedule',index=(slides[key]||0)%3;return panel(key,['A seguir','Resultados anteriores','Status do clube'][index],index===0?fixtures(web().upcoming):index===1?fixtures(web().previous):status(),3,'schedule-card');}
function competitionPage(){const c=selectedCompetition();return `<div class="career-grid competition-grid"><div class="dash-stack">${panel('goals','Artilheiros',leaderRows(c?.goals,'G'))}${panel('assists','Assistências',leaderRows(c?.assists,'A'))}</div>${competitionTable()}${schedule()}</div>`;}
function pitch(){const starts=d().starters||[],lookup=new Map(players().map(p=>[p.id,p]));return `<div class="tactical-field"><svg viewBox="0 0 300 430" preserveAspectRatio="none" aria-hidden="true"><rect x="12" y="12" width="276" height="406" rx="3"/><path d="M12 215h276M70 12v70h160V12M70 418v-70h160v70M110 12v26h80V12M110 418v-26h80v26"/><circle cx="150" cy="215" r="40"/><circle cx="150" cy="215" r="2"/></svg>${starts.map(s=>{const p={...lookup.get(s.id),...s};return `<button data-player="${p.id}" class="field-player" style="left:${10+(s.x??.5)*80}%;top:${8+(1-(s.y??.5))*84}%"><span class="field-player-number">${val(p.number)}</span>${img(p.portrait,p.name)}<b>${esc(p.name?.split(' ').slice(-1).join(' ')||'')}</b><span class="field-player-condition"><i style="width:${typeof p.condition==='number'?p.condition:0}%"></i></span><small>${typeof p.form==='number'?(p.form>0?'↗':p.form<0?'↘':'→'):'—'} ${val(p.overall)}</small></button>`;}).join('')||'<div class="dash-empty">Formação não informada.</div>'}</div>`;}
function highlightStat(p,key){const direct=p.stats?.[key]??p[key];if(typeof direct==='number')return direct;const row=web().clubStats?.[key]?.find(r=>Number(r.player??r.id)===Number(p.id));return row?.value;}
function highlights(){const list=[...players()].sort((a,b)=>(b.overall||0)-(a.overall||0)).slice(0,5);return `<div class="highlight-toolbar"><button data-dashboard-action="open-roster">Ver elenco completo ›</button></div><div class="club-highlight-cards">${list.map(p=>{const gk=p.positionId===0||p.position==='GOL',stats=gk?[['appearances','J'],['saves','DEF']]:[['goals','G'],['assists','A']];return `<button data-player="${p.id}" class="club-highlight" style="--club-color:${(d().primary||[35,65,91]).join(',')}"><div class="highlight-art"><span class="highlight-number">${val(p.number)}<small>${esc(p.position)}</small></span>${img(p.portrait||`assets/players/${p.id}.webp`,p.name,'highlight-portrait')}${crest(ctx.clubId,ctx.clubName,'highlight-crest')}<span class="highlight-ovr">${val(p.overall)}<small>OVR</small></span><strong>${esc(p.name)}</strong></div><div class="highlight-season"><div>${stats.map(([key,label])=>`<span><b>${val(highlightStat(p,key))}</b><small>${label}</small></span>`).join('')}</div><small>${gk?'Jogos · defesas':'Gols · assistências'}</small></div></button>`;}).join('')}</div>`;}

const statTypes=[['goals','Artilheiros','G'],['assists','Assistências','A'],['overall','Classificação geral','OVR'],['minutes','Minutos jogados','MIN'],['yellow','Cartões amarelos','▰'],['red','Cartões vermelhos','▰'],['oldest','Jogadores mais velhos','ANOS']];
function statsCarousel(){const [key,title,unit]=statTypes[(slides.stats||0)%statTypes.length];const rows=key==='overall'?[...players()].sort((a,b)=>b.overall-a.overall).map(p=>({...p,value:p.overall})):key==='oldest'?[...players()].filter(p=>typeof p.age==='number').sort((a,b)=>b.age-a.age).map(p=>({...p,value:p.age})):web().clubStats?.[key];return panel('stats',title,`<div class="stat-category ${key}">${leaderRows(rows,unit)}</div>`,statTypes.length);}
function rosterSummary(){const list=players(),ages=list.filter(p=>typeof p.age==='number'),ratings=list.filter(p=>typeof p.overall==='number'),groups=[['Goleiros',p=>p.positionId===0],['Defensores',p=>p.positionId>0&&p.positionId<=8],['Meias',p=>p.positionId>=9&&p.positionId<=22],['Pontas',p=>p.positionId===23||p.positionId===27],['Atacantes',p=>p.positionId>=24&&p.positionId<=26]];return `<button class="squad-summary" data-dashboard-action="open-roster"><div class="squad-summary-numbers"><span><b>${list.length}</b>Jogadores</span><span><b>${ages.length?Math.round(ages.reduce((n,p)=>n+p.age,0)/ages.length):'—'}</b>Média de idade</span><span><b>${ratings.length?Math.round(ratings.reduce((n,p)=>n+p.overall,0)/ratings.length):'—'}</b>Nota média</span></div><div class="squad-positions">${groups.map(([n,fn])=>`<span><b>${list.filter(fn).length}</b>${n}</span>`).join('')}</div><strong>Abrir elenco ›</strong></button>`;}
function injuries(){return web().injuries?.length?`<div class="dash-injuries">${web().injuries.map(r=>`<button data-player="${r.player}"><strong>${esc(r.name)}</strong><small>${esc(r.injury||'Lesão não detalhada')}</small><b>Retorno: ${esc(r.returnLabel||'não informado')}</b></button>`).join('')}</div>`:'<div class="dash-empty">Nenhuma lesão informada nesta fonte da carreira.</div>';}
function squadCarousel(){const index=(slides.squad||0)%2;return panel('squad',index?'Jogadores lesionados':'Elenco',index?injuries():rosterSummary(),2);}
function seasonCarousel(){const index=(slides.season||0)%3,s=index===1?d().season?.home:index===2?d().season?.away:d().season,form=(s?.form||web().previous?.filter(m=>index===0||index===1&&m.home===ctx.clubId||index===2&&m.away===ctx.clubId).map(m=>{const a=String(m.score||'').match(/^(\d+)\s*[-:]\s*(\d+)$/);if(!a)return null;const own=m.home===ctx.clubId?+a[1]:+a[2],other=m.home===ctx.clubId?+a[2]:+a[1];return own>other?'V':own<other?'D':'E';}).filter(Boolean)||[]).slice(0,10);return panel('season',`Desempenho · ${['Geral','Casa','Fora'][index]}`,`<div class="season-mini-numbers">${[['Jogos','games'],['Vitórias','wins'],['Empates','draws'],['Derrotas','losses'],['Gols pró','goalsFor'],['Gols contra','goalsAgainst']].map(([n,k])=>`<span><b>${val(s?.[k])}</b>${n}</span>`).join('')}</div><div class="season-mini-bottom">${ring(rate(s),'Aproveitamento')}<div><div class="form-dots">${form.map(v=>`<span class="${v}">${esc(v)}</span>`).join('')||'<small>Sem resultados registrados</small>'}</div><small>Últimos jogos${index?' · '+['','em casa','fora'][index]:''}</small></div></div>`,3);}
function competitionCarousel(){const list=web().competitions?.length?web().competitions:d().competitions||[],i=(slides.clubCompetitions||0)%Math.max(list.length,1),c=list[i],row=c?.table?.find(r=>Number(r.team)===Number(ctx.clubId));return panel('clubCompetitions','Competições do clube',c?`<button class="club-competition-summary" data-dashboard-action="open-competition:${c.root}">${img(c.asset?`icons/leagues/${c.asset}.webp`:'',c.name)}<h3>${esc(c.name)}</h3><strong>${row?val(row.rank)+'º colocado':'Classificação não informada'}</strong>${ring(row?rate(row):null,'Aproveitamento')}<small>${row?val(row.points)+' pontos':'Sem estatísticas registradas'}</small></button>`:'<div class="dash-empty">Nenhuma competição identificada.</div>',Math.max(list.length,1));}
function kitStadiumCarousel(){const i=(slides.facilities||0)%2;return panel('facilities',i?'Estádio':'Uniformes',i?`<div class="club-stadium">${img(d().stadium?.image,d().stadium?.name)}<h3>${esc(d().stadium?.name||'Estádio não informado')}</h3><small>Capacidade ${typeof d().stadium?.capacity==='number'?d().stadium.capacity.toLocaleString('pt-BR'):'—'}</small></div>`:`<div class="real-kits">${(d().kits||[]).map(k=>`<div>${img(k.image,k.name)}<strong>${esc(k.name)}</strong>${!k.image?'<small>Imagem não encontrada</small>':''}</div>`).join('')}</div>`,2);}
function teamRatings(){const detail=d(),stars=Math.max(0,Math.min(5,Number(detail.reputation||0)/4));const color=v=>typeof v==='number'?`hsl(${Math.max(0,Math.min(125,(v-45)*125/45))} 68% 59%)`:'var(--muted)';return `<section class="team-rating-strip" aria-label="Força do time"><div class="team-rating-box team-rating-general"><small>GERAL</small><div><strong style="color:${color(detail.overall)}">${val(detail.overall)}</strong><span class="team-reputation" role="img" aria-label="Reputação ${stars} de 5 estrelas">${Array.from({length:5},(_,i)=>`<span style="--star-fill:${Math.max(0,Math.min(1,stars-i))*100}%">★</span>`).join('')}</span></div></div>${[['Ataque','attack'],['Meio-campo','midfield'],['Defesa','defense']].map(([label,key])=>`<div class="team-rating-box"><small>${label}</small><strong style="color:${color(detail[key])}">${val(detail[key])}</strong></div>`).join('')}</section>`;}
function teamPage(){return `${teamRatings()}<div class="career-grid my-team-grid">${statsCarousel()}<button class="panel dash-card team-scene-card span-two" data-dashboard-action="team-options"><div class="dash-card-heading"><h2>Seu time em campo</h2><small>${esc(d().formation||'')}</small></div><div class="team-scene-image">${d().lineupScene?img(d().lineupScene,'Onze titulares em 3D'):'<div class="card-loading">'+esc(ctx.renderError||'Preparando seus 11 titulares…')+'</div>'}</div><span>Onze titulares · abrir visualização ›</span></button>${panel('pitch','Time titular',pitch(),1,'pitch-card')}${squadCarousel()}${panel('highlights','Destaques do elenco',highlights(),1,'span-two')}${kitStadiumCarousel()}${competitionCarousel()}${panel('season-container','Temporada',seasonCarousel(),1,'span-two')}${panel('club-link','Meu clube',`<button class="start" data-dashboard-action="club-info">Informações do clube ›</button>`)}</div>`;}
function rosterPage(){const list=players(),ids=new Set((d().starters||[]).map(p=>p.id)),groups=[['Titulares',p=>ids.has(p.id)||p.squadPosition>=0&&p.squadPosition<28],['Reservas',p=>p.squadPosition===28],['Não relacionados',p=>p.squadPosition===29],['Situação não informada',p=>!ids.has(p.id)&&(p.squadPosition==null||p.squadPosition<0||p.squadPosition>29)]];return `<div class="career-grid roster-layout"><section class="roster-list"><div class="eyebrow">${esc(ctx.clubName)}</div><h2>Meu elenco</h2>${groups.map(([name,fn])=>{const rows=list.filter(fn);return !rows.length&&name==='Situação não informada'?'':`<section class="roster-group"><h3>${name}<small>${rows.length}</small></h3>${rows.map(p=>`<button data-player="${p.id}" class="roster-player"><span class="roster-overall" style="--rating-hue:${Math.max(0,Math.min(130,(p.overall-40)*3))}"><b>${val(p.overall)}</b><small>OVR</small></span>${img(p.portrait||`assets/players/${p.id}.webp`,p.name,'roster-portrait')}<div><strong>${esc(p.name)}</strong><span>${flag(p)}${esc(ctx.clubName)}</span><div class="roster-tags"><b>${esc(p.position)}</b><b>POT ${val(p.potential)}</b><b>#${val(p.number)}</b></div></div></button>`).join('')||'<div class="dash-empty">Nenhum jogador neste grupo.</div>'}</section>`;}).join('')}</section><div class="roster-free-slots" aria-hidden="true"></div></div>`;}
function html(tab,context){if(ctx.saveRevision!==context.saveRevision||ctx.clubId!==context.clubId){clubs.clear();loading.clear();}ctx=context;active=tab;if(ctx.clubId)clubs.set(Number(ctx.clubId),d());return tab==='home'?`<div class="career-grid home-grid">${nextMatch()}${news()}${coach()}<section class="scenes">${[['press','Sala de coletiva'],['locker','Vestiário'],['gym','Academia'],['training','Centro de treinamento']].map(([key,label])=>`<button class="scene-button" data-action="scene:${key}">${d().rooms?.[key]?img(d().rooms[key],label):'<div class="card-loading">'+esc(d().roomErrors?.[key]||(!ctx.renderPending&&ctx.saveRevision?'Ambiente indisponível para este clube.':'Preparando ambiente…'))+'</div>'}<strong>${label}</strong></button>`).join('')}</section></div>`:tab==='competitions'?competitionPage():tab==='teams'?teamPage():rosterPage();}
function replace(key,content){const target=document.querySelector(`[data-dashboard-panel="${key}"]`);if(target){const temp=document.createElement('template');temp.innerHTML=content;const focused=target.dataset.focused==='true',domFocus=target.contains(document.activeElement);const next=temp.content.firstElementChild;next.dataset.focused=String(focused);target.replaceWith(next);onChange();bindNews();if(focused)next.dispatchEvent(new Event('pointerenter'));if(domFocus)next.focus({preventScroll:true});}}
function mount(context,rebind){ctx=context;onChange=rebind;bindNews();if(active==='home'){const canvas=document.querySelector('[data-coach-3d]');if(canvas){coachCanvas=canvas;FFClubData.model(ctx.clubId,0,201).then(url=>{if(canvas.isConnected)return FFPlayer3D.load(canvas,url).then(()=>canvas.previousElementSibling?.setAttribute('hidden',''));}).catch(()=>{if(canvas.isConnected){const note=canvas.parentElement.querySelector('.card-loading');if(note)note.textContent='Modelo 3D deste treinador indisponível nos assets.';}});}const m=match();for(const id of [m?.home,m?.away])if(id&&!clubs.has(id)&&!loading.has(id)){loading.add(id);FFClubData.metadata(id).then(data=>{if(data)clubs.set(id,data);if(active==='home')replace('match',nextMatch());}).catch(()=>{}).finally(()=>loading.delete(id));}}else if(coachCanvas&&!coachCanvas.isConnected&&!modal){FFPlayer3D.dispose();coachCanvas=null;}}
function closeModal(){++modalRevision;if(modal){modal.remove();modal=null;FFPlayer3D.dispose();onChange();}}
function openModal(mode){closeModal();modalMode=mode;modal=document.createElement('section');modal.className='team-photo-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-label','Visualização do time');modal.innerHTML=mode==='options'?`<div class="panel team-photo-options"><h2>Seu time em campo</h2><button class="start" data-dashboard-action="team-view:xi">Onze titulares · alta qualidade</button><button class="start" data-dashboard-action="team-view:squad">Elenco completo com o técnico</button><small>B / Esc · voltar</small></div>`:`<div class="team-photo-content"><h2>${mode==='squad'?'Elenco completo e comissão técnica':'Onze titulares'}</h2><div class="team-photo-frame"><canvas data-team-photo data-framing="group" data-readonly="true" hidden aria-label="Cena 3D do elenco"></canvas><span data-team-loading>Preparando a cena 3D…</span></div>${mode==='xi'?'<button class="circle" data-dashboard-action="team-pose" aria-label="Trocar pose">↻</button>':''}<small>${mode==='xi'?'X / P · trocar pose · ':''}B / Esc · voltar</small></div>`;document.body.append(modal);document.querySelector('#dashboard').inert=true;document.querySelector('.topbar').inert=false;onChange();modal.querySelector('button')?.focus();if(mode!=='options')loadTeam();}
function loadTeam(){const token=++modalRevision,canvas=modal?.querySelector('[data-team-photo]');if(!canvas)return;FFClubData.team(ctx.clubId,modalMode,modalMode==='squad'?120:pose).then(url=>{if(token===modalRevision&&canvas.isConnected)return FFPlayer3D.load(canvas,url).then(()=>canvas.previousElementSibling?.setAttribute('hidden',''));}).then(()=>{if(token===modalRevision)modal?.querySelector('[data-team-loading]')?.setAttribute('hidden','');}).catch(error=>{if(token===modalRevision)modal.querySelector('[data-team-loading]').textContent='Não foi possível carregar esta cena: '+error.message;});}
function dismiss(){if(!modal)return false;closeModal();document.querySelector('#dashboard').inert=false;document.querySelector('.topbar').inert=false;onChange();return true;}
function handle(action){const [kind,key,value]=String(action).split(':');if(kind==='slide'||kind==='goto'){if(key==='news')newsElapsed=0;const count=key==='news'?newsItems().length:key==='stats'?statTypes.length:key==='schedule'||key==='season'?3:key==='clubCompetitions'?Math.max((web().competitions||d().competitions||[]).length,1):2;slides[key]=kind==='goto'?Number(value):((slides[key]||0)+Number(value)+count)%count;const renderers={news,stats:statsCarousel,schedule,squad:squadCarousel,season:seasonCarousel,clubCompetitions:competitionCarousel,facilities:kitStadiumCarousel};replace(key,renderers[key]());return true;}if(kind==='competition'){competitionId=key;return 'refresh';}if(kind==='open-competition'){competitionId=key;return 'competitions';}if(kind==='open-roster')return 'players';if(kind==='club-info')return 'club-info';if(kind==='team-options'){openModal('options');return true;}if(kind==='team-view'){openModal(key);return true;}if(kind==='team-pose'&&modalMode==='xi'){const choices=[1,2,3,4,5,6,7].filter(v=>v!==pose);pose=choices[Math.floor(Math.random()*choices.length)];loadTeam();return true;}return false;}
function tickNews(now){const delta=Math.min(now-newsLastTick,100);newsLastTick=now;const card=document.querySelector('[data-dashboard-panel="news"]');if(active==='home'&&card&&!document.hidden&&!modal){const paused=card.matches(':hover,:focus-within');if(!paused)newsElapsed+=delta;const timer=card.querySelector('.news-progress'),progress=Math.min(100,newsElapsed/NEWS_DURATION*100);if(timer){timer.style.setProperty('--news-progress',progress+'%');timer.setAttribute('aria-valuenow',String(Math.round(progress)));timer.classList.toggle('paused',paused);}if(newsElapsed>=NEWS_DURATION)handle('slide:news:1');}requestAnimationFrame(tickNews);}requestAnimationFrame(tickNews);
window.FFCareerDashboard={html,mount,handle,dismiss,get modalOpen(){return !!modal;},pose:()=>handle('team-pose')};
})();
