(() => {
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let context={},tab=0,portrait=false,pose=201,busy=false,revision=0;
const fact=(label,value)=>`<div><span>${esc(label)}</span><strong>${esc(value??'—')}</strong></div>`;
function render(value){context=value;const serial=++revision;if(Number(new URLSearchParams(location.search).get('club'))!==Number(context.clubId)){document.getElementById('profile-body').innerHTML='<div class="notice">Carregando o treinador…</div>';return;}const d=context.detail||{},coach=d.coach||{},name=coach.name||'Treinador do clube',body=document.getElementById('profile-body');
 const summary=`<div class="profile-details">${fact('Clube',context.clubName)}${fact('Nacionalidade',coach.country||'—')}${fact('Liga',coach.league||'—')}${fact('Confiança',coach.confidence>=0?coach.confidence:'—')}${fact('Salário semanal',coach.weeklyWage>0?coach.weeklyWage.toLocaleString('pt-BR'):'—')}${fact('Reputação',coach.reputation>=0?coach.reputation.toFixed(1)+' / 5':'—')}${fact('Formação do time',d.formation||'—')}${fact('Estádio do clube',d.stadium?.name||'—')}</div>`;
 const season=d.season,history=d.history||[];const stats=season?`<div class="profile-summary-ratings">${[['Jogos',season.games],['Vitórias',season.wins],['Empates',season.draws],['Derrotas',season.losses],['Gols pró',season.goalsFor],['Gols contra',season.goalsAgainst]].map(([n,v])=>fact(n,v)).join('')}</div>`:'<div class="profile-empty">A temporada deste clube não está registrada nesta fonte do save.</div>';
 const competitionTable=`<h2>Competições do clube</h2><table class="profile-stats"><thead><tr><th>Competição</th><th>J</th><th>V</th><th>E</th><th>D</th></tr></thead><tbody>${(d.competitions||[]).map(row=>`<tr><th>${esc(row.name)}${row.recorded===false?'<small class="stats-pending">Sem estatísticas registradas</small>':''}</th>${['games','wins','draws','losses'].map(k=>`<td>${row[k]??0}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="5">Nenhuma competição identificada nesta fonte do save.</td></tr>'}</tbody></table>`;
 const records=history.length?`<table class="profile-stats"><thead><tr><th>Temporada</th><th>J</th><th>V</th><th>E</th><th>D</th><th>Pontos</th></tr></thead><tbody>${history.map(row=>`<tr><th>${esc(row.season)}</th>${['games','wins','draws','losses','points'].map(k=>`<td>${esc(row[k]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'';
 const oldActor=body.querySelector('.profile-actor'),owner=String(context.clubId)+':'+String('coach');
 body.innerHTML=`<div class="profile-layout"><section class="profile-actor"><img class="profile-watermark" src="crests/${context.clubId}.webp" alt=""><canvas id="player-model-canvas" data-nav-item tabindex="0" hidden aria-label="Modelo 3D interativo do treinador"></canvas><img id="player-render" class="${portrait?'portrait':''}" src="${esc(portrait?coach.photo:coach.model||coach.photo||'')}" alt="${esc(name)}" onerror="this.hidden=true"><div class="profile-actor-actions"><button data-profile-action="pose">Trocar pose</button><button data-profile-action="portrait">${portrait?'Ver modelo 3D':'Ver retrato'}</button></div></section><section class="profile-information"><nav class="profile-tabs">${['Resumo','Temporada do clube'].map((n,i)=>`<button data-profile-tab="${i}" class="${tab===i?'active':''}">${n}</button>`).join('')}</nav><header class="profile-title"><div><div class="eyebrow">Treinador</div><h1>${esc(name)}</h1><div class="profile-club"><img src="crests/${context.clubId}.webp" alt="">${esc(context.clubName)} · ${coach.nationId?`<img class="nationality-flag" src="icons/countries/${coach.nationId}.webp" alt="${esc(coach.country)}" onerror="this.hidden=true">`:''}${esc(coach.country||'')}</div></div></header><div class="profile-content">${tab===0?summary+(window.FFSeasonCharts?.render(d)||''):`<h2>Temporada do clube</h2>${stats}${competitionTable}${records}`}</div></section></div>`;
 const newActor=body.querySelector('.profile-actor');if(oldActor?.dataset.owner===owner&&oldActor.dataset.portrait===String(portrait)){const oldBio=oldActor.querySelector('.profile-bio'),newBio=newActor.querySelector('.profile-bio');if(oldBio&&newBio)oldBio.innerHTML=newBio.innerHTML;newActor.replaceWith(oldActor);}else{newActor.dataset.owner=owner;newActor.dataset.portrait=String(portrait);}
 if(!portrait)FFClubData.model(context.clubId,0,pose).then(url=>{if(serial===revision&&!portrait)return FFPlayer3D.load(document.getElementById('player-model-canvas'),url);}).catch(error=>console.error('Modelo do treinador:',error));else FFPlayer3D.dispose();
 body.querySelectorAll('[data-profile-tab]').forEach(b=>b.onclick=()=>{tab=Number(b.dataset.profileTab);render(context);window.dispatchEvent(new Event('ff-profile-render'));});body.querySelectorAll('[data-profile-action]').forEach(b=>b.onclick=()=>action(b.dataset.profileAction));
}
function action(key){if(key==='model'){if(portrait){portrait=false;render(context);}}else if(key==='portrait'){portrait=!portrait;render(context);}else if(key==='pose'){if(busy)return;portrait=false;const poses=[201,202,203,204,208,209,210].filter(v=>v!==pose);pose=poses[Math.floor(Math.random()*poses.length)];busy=true;const button=document.querySelector('[data-profile-action=pose]');if(button){button.disabled=true;button.textContent='Atualizando pose…';}FFClubData.model(context.clubId,0,pose).then(url=>FFPlayer3D.load(document.getElementById('player-model-canvas'),url)).catch(error=>console.error(error)).finally(()=>{busy=false;const button=document.querySelector('[data-profile-action=pose]');if(button){button.disabled=false;button.textContent='Trocar pose';}window.dispatchEvent(new Event('ff-profile-render'));});}else if(key==='previous'||key==='next'){tab=1-tab;render(context);}window.dispatchEvent(new Event('ff-profile-render'));}
window.FFPlayerProfile={render,action};
})();
