(() => {
const embedded=!!window.chrome?.webview,page=document.body.dataset.page;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const offline=window.FF_PREVIEW_CONTEXT||{};let context={},tab=new URLSearchParams(location.search).get('tab')||'home',focus=0,newsIndex=0,playerOffset=0,buttons=[],previous=[],repeatAt=0,lastDirection=0,blobUrl='';
const tabTrail=[];
const tabs=['home','competitions','leagues','teams','players','calendar','transfers'];
const detail=()=>context.detail||{};
const image=(src,alt,css='')=>src?`<img class="${css}" src="${esc(src)}" alt="${esc(alt)}" onerror="this.hidden=true">`:'';
function send(action){if(embedded){window.chrome.webview.postMessage(action);return;}if(action.startsWith('coach:')){const [,club,from]=action.split(':');sessionStorage.setItem('ff-return-tab',from||tab);sessionStorage.setItem('ff-return-club',club);location.href='coach.html?club='+encodeURIComponent(club);}else if(action.startsWith('player:')){const [,id,from,club]=action.split(':');sessionStorage.setItem('ff-return-tab',from||'players');if(club)sessionStorage.setItem('ff-return-club',club);location.href='player.html?id='+encodeURIComponent(id)+'&club='+(club||context.clubId||'');}else if(action==='start')location.href='/central';else if(action==='clubs')setTab('leagues');else if(action==='back')location.href=page==='player'?'/central?tab='+(sessionStorage.getItem('ff-return-tab')||'players')+(['leagues','teams'].includes(sessionStorage.getItem('ff-return-tab'))?'&club='+sessionStorage.getItem('ff-return-club'):''):page==='scene'?'/central':'/inicio';else if(action.startsWith('scene:'))location.href='scene.html?room='+action.split(':')[1];}
let activeInputPad=null;function controls(pad){activeInputPad=pad;const family=/sony|054c|dualshock|dualsense|playstation/i.test(pad?.id||'')?'playstation':'xbox';const game=!!pad;
const actions=game?[{key:family==='playstation'?'×':'A',face:family==='playstation'?'cross':'a',family,label:page==='home'?'Começar':'Abrir'},{key:family==='playstation'?'○':'B',face:family==='playstation'?'circle':'b',family,label:'Voltar'}]:[{key:'Enter',label:page==='home'?'Começar':'Abrir'},{key:'Esc',label:'Voltar'}];
if(page==='scene'||page==='player')actions.shift();if(page==='scene')actions.push(...(game?[{key:'R',family:'stick',label:'Olhar'},{key:'L',family:'stick',label:'Andar'},{key:'LT / RT',label:'Zoom'},{key:'Y',face:'y',family,label:'Centralizar câmera'}]:[{key:'Mouse',label:'Olhar'},{key:'W A S D',label:'Andar'},{key:'Shift',label:'Correr'},{key:'Roda',label:'Zoom'},{key:'R',label:'Centralizar câmera'}]));if(page==='player')actions.push(...(game?[{key:'X',face:'x',family,label:'Pose'},{key:'Y',face:'y',family,label:'Segurar: mover 3D'},{key:'LB / RB',label:'Abas'},{key:'R',family:'stick',label:'Girar / altura com Y'},{key:'LT / RT',label:'Zoom com Y'}]:[{key:'P',label:'Pose'},{key:'Q / E',label:'Abas'}]));
if(page==='central'&&tab==='calendar')actions.push(game?{key:family==='playstation'?'L2 / R2':'LT / RT',label:'Mudar mês'}:{key:'← / →',label:'Mudar mês'});
if(page==='central'&&FFCareerDashboard.modalOpen){actions.splice(0,actions.length,...(game?[{key:'X',face:'x',family,label:'Trocar pose'},{key:'B',face:'b',family,label:'Voltar'}]:[{key:'P',label:'Trocar pose'},{key:'Esc',label:'Voltar'}]));}else if(page==='central')actions.push(game?{key:family==='playstation'?'L1 / R1':'LB / RB',label:'Alternar abas'}:{key:'Q / E',label:'Alternar abas'});
if(page==='central'&&buttons[focus]?.dataset.dashboardPanel==='news')actions.unshift(game?{key:'R',family:'stick',label:'Passar notícias'}:{key:'← / →',label:'Passar notícias'});
document.querySelector('ff-control-hints')?.configure({mode:game?'gamepad':'keyboard',controllerId:pad?.id||'',actions});}
function bind(){const old=buttons[focus];buttons=[...document.querySelectorAll('button,[data-nav-item]')].filter(b=>FFSpatialNavigation.usable(b));focus=buttons.includes(old)?buttons.indexOf(old):Math.min(focus,Math.max(0,buttons.length-1));buttons.forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='true';b.addEventListener('pointerenter',()=>{setFocus(buttons.indexOf(b),false);if(b.dataset.player)FFClubData.model(context.clubId,Number(b.dataset.player),101).catch(()=>{});if(b.dataset.action==='coach')FFClubData.model(context.clubId,0,201).catch(()=>{});});b.addEventListener('focus',()=>setFocus(buttons.indexOf(b),false));if(!b.dataset.tab)b.addEventListener('click',()=>act(b));});setFocus(focus,false);controls(activeInputPad);}
function setFocus(index,move=true){if(!buttons.length)return;focus=(index+buttons.length)%buttons.length;buttons.forEach((b,i)=>b.dataset.focused=String(i===focus));controls(activeInputPad);if(move){buttons[focus].focus({preventScroll:true});buttons[focus].scrollIntoView({block:'nearest',inline:'nearest'});}}
function moveFocus(direction){const next=FFSpatialNavigation.next(buttons,buttons[focus],direction);if(next)setFocus(buttons.indexOf(next));}
window.addEventListener('ff-profile-render',bind);
function updateIdentity(){document.querySelectorAll('[data-club]').forEach(e=>e.textContent=context.clubName||'Carreira');document.querySelectorAll('[data-crest]').forEach(e=>{e.hidden=!context.clubId;if(context.clubId)e.src=`crests/${context.clubId}.webp`;e.onerror=()=>e.hidden=true;});}
function playerCard(p){return `<button class="player" data-player="${esc(p.id)}"><span class="rating">${esc(p.overall)}</span>${image(p.portrait||`assets/players/${p.id}.webp`,p.name)}<strong>${esc(p.name)}</strong><small class="muted">${esc(p.position||'')}</small></button>`;}
function dashboard(){return FFCareerDashboard.html(tab,context);}
function render(){updateIdentity();if(page==='home')loadEntryTeam();
if(page==='central'){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const host=document.getElementById('dashboard');if(tab==='leagues'){if(host.querySelector('iframe')?.dataset.tab!==tab)host.innerHTML=`<div class="league-workspace"><nav class="league-submenu" aria-label="Submenu de ligas"><span class="league-submenu-label">Ligas</span><button data-action="league-explore" aria-current="page">Explorar clubes</button></nav><iframe data-tab="${tab}" src="index.html${tab==='teams'?'?view=club&club='+(Number(new URLSearchParams(location.search).get('club'))||context.clubId||''):(new URLSearchParams(location.search).has('club')?'?restore=1':'')}" title="${tab==='teams'?'Meu time':'Explorar ligas'}"></iframe></div>`;host.querySelector('iframe')?.addEventListener('load',()=>host.querySelector('iframe')?.contentWindow.postMessage({type:'ff-career',context},'*'));host.querySelector('iframe')?.contentWindow.postMessage({type:'ff-career',context},'*');}else if(['home','competitions','teams','players','calendar'].includes(tab)){const oldCoach=host.querySelector('[data-coach-3d]');host.innerHTML=tab==='calendar'?FFCareerCalendar.html(context):dashboard();const newCoach=host.querySelector('[data-coach-3d]');if(oldCoach&&newCoach&&oldCoach.dataset.club===String(context.clubId)&&oldCoach.dataset.saveRevision===String(context.saveRevision||'live'))newCoach.replaceWith(oldCoach);else if(newCoach){newCoach.dataset.club=context.clubId;newCoach.dataset.saveRevision=String(context.saveRevision||'live');}FFCareerDashboard.mount(context,bind);}else host.innerHTML=`<section class="panel"><h2>Transferências</h2><p class="muted">${embedded?'Acompanhe o mercado e as transferências da carreira.':'As operações de transferência precisam da carreira aberta no FIFA. Você pode conferir o elenco salvo na aba Jogadores.'}</p>${embedded?'<button class="start" data-action="screen:transfers">Abrir mercado de transferências</button>':''}</section>`;}
if(page==='player')window.FFPlayerProfile?.render(context);
if(page==='scene')loadRoomScene();
bind();}
let entryOwner='',entryToken=0;
async function loadEntryTeam(){if(!context.clubId)return;const owner=[context.saveRevision||'live',context.clubId].join(':');if(owner===entryOwner)return;entryOwner=owner;const token=++entryToken,canvas=document.getElementById('xi-model'),card=document.getElementById('lineup-card'),note=card.querySelector('.empty');card.classList.remove('has-image');canvas.hidden=true;note.textContent='Preparando seus 11 titulares…';FFPlayer3D.dispose();try{const url=await FFClubData.model(context.clubId,-1,1);if(token!==entryToken)return;await FFPlayer3D.load(canvas,url);if(token!==entryToken)return;card.classList.add('has-image');}catch(error){if(token===entryToken){note.textContent='Não foi possível carregar seus titulares em 3D: '+error.message;entryOwner='';}}}
let roomOwner='',roomToken=0;
async function loadRoomScene(){if(!context.clubId)return;const kind=new URLSearchParams(location.search).get('room')||'press',owner=[context.saveRevision,context.clubId,kind].join(':');if(owner===roomOwner)return;roomOwner=owner;const token=++roomToken,canvas=document.getElementById('room-canvas'),note=document.getElementById('room-unavailable');FFPlayer3D.dispose();canvas.hidden=true;note.hidden=false;note.textContent='Preparando ambiente 3D do clube…';try{const response=await fetch('http://127.0.0.1:8876/api/rooms/'+context.clubId+'/'+kind+(embedded?'?source=game&activeClub='+encodeURIComponent(sessionStorage.getItem('ff-live-club')||context.clubId||0):''));const result=await response.json();if(!response.ok)throw new Error(result.error);if(token!==roomToken)return;await FFPlayer3D.load(canvas,result.image);if(token!==roomToken)return;note.hidden=true;canvas.dataset.focused='true';canvas.focus({preventScroll:true});}catch(error){if(token===roomToken)note.textContent='Não foi possível abrir este ambiente: '+error.message;}}
let clubOverlay=null;function closeClubOverlay(){if(!clubOverlay)return;clubOverlay.remove();clubOverlay=null;const base=document.querySelector('#dashboard iframe');document.getElementById('dashboard').inert=false;if(base)base.inert=false;const header=document.querySelector('.topbar');if(header)header.inert=false;base?.contentWindow.postMessage({type:'ff-suspend',paused:false},'*');bind();if(base)base.focus();else buttons[focus]?.focus({preventScroll:true});}
function openClubOverlay(id){closeClubOverlay();const base=document.querySelector('#dashboard iframe');document.getElementById('dashboard').inert=true;if(base)base.inert=true;const header=document.querySelector('.topbar');if(header)header.inert=false;base?.contentWindow.postMessage({type:'ff-suspend',paused:true},'*');clubOverlay=document.createElement('section');clubOverlay.className='club-page-overlay';clubOverlay.setAttribute('role','dialog');clubOverlay.setAttribute('aria-label','Informações do clube');let savedLeague='';try{savedLeague=JSON.parse(sessionStorage.getItem('ff-globe-state'))?.leagueId||'';}catch{}clubOverlay.innerHTML=`<iframe src="index.html?view=club&club=${Number(id)}&league=${encodeURIComponent(savedLeague)}&overlay=1" title="Informações do clube"></iframe>`;document.body.append(clubOverlay);const child=clubOverlay.querySelector('iframe');child.onload=()=>{child.focus();child.contentWindow.postMessage({type:'ff-career',context},'*');child.contentWindow.postMessage({type:'ff-activate'},'*');};}
function setTab(key,nested=false){if(!tabs.includes(key))return;const hadLayer=!!clubOverlay||FFCareerDashboard.modalOpen;closeClubOverlay();FFCareerDashboard.dismiss();if(tab===key){if(hadLayer)bind();return;}if(nested)tabTrail.push(tab);else tabTrail.length=0;tab=key;if(!embedded){const url=new URL(location.href);url.pathname='/central';url.searchParams.set('tab',tab);url.searchParams.delete('club');history.replaceState({tab},'',url);}focus=0;render();}
function goBack(){if(clubOverlay){closeClubOverlay();return;}if(FFCareerDashboard.dismiss())return;if(tabTrail.length){setTab(tabTrail.pop(),true);tabTrail.pop();return;}if(tab!=='home')setTab('home');else send('back');}
function act(b){if(b?.dataset.tab){setTab(b.dataset.tab);return;}const action=b?.dataset.action;if(action?.startsWith('calendar-month:')){FFCareerCalendar.move(Number(action.split(':')[1]));render();return;}if(action?.startsWith('calendar-day:')){FFCareerCalendar.select(Number(action.split(':')[1]));render();return;}if(action==="league-explore"){document.querySelector("#dashboard iframe")?.focus();return;}if(b?.dataset.player){send('player:'+b.dataset.player+':'+tab+':'+(b.dataset.playerClub||context.clubId));return;}
if(b?.dataset.dashboardAction){const result=FFCareerDashboard.handle(b.dataset.dashboardAction);if(result==='refresh'){render();return;}if(result==='club-info'){openClubOverlay(context.clubId);return;}if(typeof result==='string'&&tabs.includes(result)){setTab(result,true);return;}if(result){bind();return;}}
if(action==='coach'){send('coach:'+context.clubId+':'+tab);return;}if(action==='team'){setTab('teams');return;}if(action==='refresh'){render();return;}if(action?.startsWith('news:')){newsIndex+=action.endsWith('next')?1:-1;newsIndex=Math.max(0,newsIndex);render();return;}if(action?.startsWith('players:')){const len=(detail().highlights||detail().players||detail().starters||[]).length;playerOffset=action.endsWith('next')?Math.min(Math.max(0,len-5),playerOffset+1):Math.max(0,playerOffset-1);render();return;}if(action)send(action);}
function key(event){if(page==='central'&&['q','e','PageUp','PageDown'].includes(event.key)){event.preventDefault();setTab(tabs[(tabs.indexOf(tab)+(['q','PageUp'].includes(event.key)?tabs.length-1:1))%tabs.length]);return;}if(page==='central'&&['Escape','Backspace'].includes(event.key)){event.preventDefault();goBack();return;}if(page==='central'&&tab==='calendar'&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();FFCareerCalendar.move(event.key==='ArrowRight'?1:-1);render();return;}if(page==='central'&&tab==='home'&&buttons[focus]?.dataset.dashboardPanel==='news'&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();FFCareerDashboard.handle('slide:news:'+(event.key==='ArrowRight'?1:-1));return;}if(page==='central'&&FFCareerDashboard.modalOpen){if(['Escape','Backspace'].includes(event.key)){event.preventDefault();FFCareerDashboard.dismiss();return;}if(event.key.toLowerCase()==='p'){event.preventDefault();FFCareerDashboard.pose();return;}if(['q','e','PageUp','PageDown'].includes(event.key)){event.preventDefault();return;}}if(clubOverlay){if(event.key==='Escape'||event.key==='Backspace'){event.preventDefault();closeClubOverlay();}return;}if(page==='player'&&['q','e','p','f'].includes(event.key.toLowerCase())){event.preventDefault();FFPlayerProfile.action(({q:'previous',e:'next',p:'pose',f:'portrait'})[event.key.toLowerCase()]);return;}if(page==='central'&&['q','e','PageUp','PageDown'].includes(event.key)){event.preventDefault();setTab(tabs[(tabs.indexOf(tab)+(['q','PageUp'].includes(event.key)?tabs.length-1:1))%tabs.length]);return;}if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(event.key)){event.preventDefault();moveFocus(event.key.slice(5).toLowerCase());}else if(event.key==='Enter'||event.key===' '){event.preventDefault();if(event.target?.dataset.tab)setTab(event.target.dataset.tab);else buttons[focus]?.click();}else if(event.key==='Escape'||event.key==='Backspace'){event.preventDefault();if(page==='central'&&tab!=='home')setTab('home');else send('back');}}
document.addEventListener('keydown',key);document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
window.addEventListener('message',event=>{const base=document.querySelector('#dashboard iframe'),overlay=clubOverlay?.querySelector('iframe');if(event.source!==base?.contentWindow&&event.source!==overlay?.contentWindow)return;if(event.data?.type==='ff-open-club')openClubOverlay(event.data.clubId);if(event.data?.type==='ff-close-club')closeClubOverlay();if(event.data?.type==='ff-back'){if(clubOverlay)closeClubOverlay();else goBack();}if(event.data?.type==='ff-coach')send('coach:'+event.data.clubId+':'+tab);if(event.data?.type==='ff-player')send('player:'+event.data.id+':'+tab+':'+event.data.clubId);if(event.data?.type==='ff-tab')setTab(tabs[(tabs.indexOf(tab)+(event.data.direction<0?tabs.length-1:1))%tabs.length]);});
window.chrome?.webview?.addEventListener('message',event=>{const data=event.data;if(data?.type==='career-context'){if(['home','central'].includes(page)&&data.clubId>0)sessionStorage.setItem('ff-live-club',String(data.clubId));if(page==='player'&&Number(new URLSearchParams(location.search).get('club'))&&Number(new URLSearchParams(location.search).get('club'))!==data.clubId)return;const assets=Number(context.clubId)===Number(data.clubId)?context.detail:{};context={...context,...data,saveRevision:Number(context.clubId)===Number(data.clubId)?context.saveRevision:undefined,live:true,detail:{...assets,...data.detail,coach:{...assets?.coach,...data.detail?.coach}}};refreshSavedCareer();if(context.detail.webDashboard?.competitions)context.detail.webDashboard.competitions=context.detail.webDashboard.competitions.map(c=>{const fallback=assets?.webDashboard?.competitions?.find(e=>e.asset===c.asset);return c.table?.length?c:{...c,table:fallback?.table||[]};});if(context.detail.webDashboard?.season)context.detail.season={...context.detail.season,...context.detail.webDashboard.season};render();}else if(data?.type==='scene-image'&&(page==='home'||page==='scene'||page==='player')){if(page==='home'){window.chrome.webview.postMessage('preview-received');return;}if(page==='scene'||Number(data.clubId)!==Number(context.clubId))return;const img=document.getElementById(page==='player'?'player-render':page==='scene'?'room-image':'xi-render');if(blobUrl)URL.revokeObjectURL(blobUrl);const raw=atob(data.data),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));blobUrl=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));if(!img)return;img.src=blobUrl;img.hidden=page==='player'&&!!document.getElementById('player-model-canvas')?.offsetHeight;img.onload=()=>{document.getElementById('lineup-card')?.classList.add('has-image');const note=document.getElementById('room-unavailable');if(note)note.hidden=true;};window.chrome.webview.postMessage('preview-received');}});
let newsStickAt=0;let lastPad='';function frame(now){const pad=[...(navigator.getGamepads?.()||[])].find(p=>p?.connected),current=pad?.buttons.map(b=>b.pressed)||[];if((pad?.id||'')!==lastPad){lastPad=pad?.id||'';controls(pad);previous=current;}if(pad&&page==='central'){if(current[4]&&!previous[4])setTab(tabs[(tabs.indexOf(tab)+tabs.length-1)%tabs.length]);if(current[5]&&!previous[5])setTab(tabs[(tabs.indexOf(tab)+1)%tabs.length]);}
if(pad&&!clubOverlay){if(page==='central'&&tab==='calendar'){const back=(pad.buttons[6]?.value||0)>.6||pad.buttons[6]?.pressed,next=(pad.buttons[7]?.value||0)>.6||pad.buttons[7]?.pressed;if(back&&!previous[6]){FFCareerCalendar.move(-1);render();}if(next&&!previous[7]){FFCareerCalendar.move(1);render();}}if(page==='central'&&tab==='home'&&!FFCareerDashboard.modalOpen&&buttons[focus]?.dataset.dashboardPanel==='news'){const rx=pad.axes[2]||0;if(Math.abs(rx)<.25)newsStickAt=0;else if(Math.abs(rx)>.55&&now>=newsStickAt){FFCareerDashboard.handle('slide:news:'+(rx>0?1:-1));newsStickAt=now+420;}}if(page==='player'){if(current[3]&&!previous[3])FFPlayerProfile.action('model');if(current[4]&&!previous[4])FFPlayerProfile.action('previous');if(current[5]&&!previous[5])FFPlayerProfile.action('next');if(current[2]&&!previous[2])FFPlayerProfile.action('pose');}if(!(page==='central'&&tab==='leagues')){const ax=pad.axes[0]||0,ay=pad.axes[1]||0;const direction=page==='player'&&current[3]?'':current[14]?'left':current[15]?'right':current[12]?'up':current[13]?'down':Math.max(Math.abs(ax),Math.abs(ay))>.5?(Math.abs(ax)>Math.abs(ay)?(ax<0?'left':'right'):(ay<0?'up':'down')):'';if(direction&&(direction!==lastDirection||now>=repeatAt)){moveFocus(direction);repeatAt=now+(direction!==lastDirection?350:180);}lastDirection=direction;if(current[0]&&!previous[0])buttons[focus]?.click();if(page==='central'&&FFCareerDashboard.modalOpen&&current[2]&&!previous[2])FFCareerDashboard.pose();if(current[1]&&!previous[1]){if(page==='central')goBack();else send('back');}if(((page==='central'&&!FFCareerDashboard.modalOpen)||(page==='player'&&!current[3]))&&Math.abs(pad.axes[3]||0)>.18)(document.getElementById('dashboard')||document.getElementById('profile-body')).scrollTop+=pad.axes[3]*12;}}previous=current;requestAnimationFrame(frame);}
async function refreshSavedCareer(){if(document.hidden)return;try{const response=await fetch('http://127.0.0.1:8876/api/career'+(embedded?'?source=game&activeClub='+encodeURIComponent(sessionStorage.getItem('ff-live-club')||context.clubId||0):''),{cache:'no-store'});const saved=await response.json();if(!response.ok)throw new Error(saved.error||'Save indisponível');if(context.saveRevision===saved.saveRevision&&context.renderPending===saved.renderPending&&context.renderError===saved.renderError&&context.detail?.lineupScene===saved.detail?.lineupScene)return;if(embedded){if(Number(context.clubId)!==Number(saved.clubId))return;const native=context.detail;context={...saved,...context,saveRevision:saved.saveRevision,renderPending:saved.renderPending,renderError:saved.renderError,detail:{...saved.detail,...native,coach:{...saved.detail?.coach,...native?.coach},webDashboard:{...saved.detail?.webDashboard,...native?.webDashboard},lineupScene:saved.detail?.lineupScene,rooms:saved.detail?.rooms}};}else context=saved;document.body.dataset.careerSource='local-save';document.body.dataset.saveSlot=saved.saveSlot;render();}catch(error){document.body.dataset.careerSource='cached-preview';console.warn('Prévia do save: '+error.message);}}
if(page==='home'&&!embedded){const entry=document.createElement('a');entry.className='preview-save-button';entry.href='/preview/save';entry.textContent='Escolher save da carreira';document.querySelector('.intro').append(entry);}
render();controls(null);requestAnimationFrame(frame);refreshSavedCareer();setInterval(refreshSavedCareer,5000);if(page==='central'&&Number(new URLSearchParams(location.search).get('club'))&&['leagues','teams'].includes(tab))openClubOverlay(Number(new URLSearchParams(location.search).get('club')));
if(page==='player'&&window.FFClubData){const club=Number(new URLSearchParams(location.search).get('club'))||context.clubId;if(club)FFClubData.load(club,d=>{if(!embedded){context={clubId:d.clubId,clubName:d.name,detail:d};render();}}).catch(()=>{});}
})();