(() => {
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=[['Ritmo',['acceleration','sprintspeed']],['Chute',['finishing','shotpower','longshots','volleys','penalties','positioning']],['Passe',['vision','crossing','shortpassing','longpassing','curve','freekickaccuracy']],['Drible',['agility','balance','reactions','ballcontrol','dribbling']],['Defesa',['interceptions','marking','standingtackle','slidingtackle','headingaccuracy']],['Físico',['strength','stamina','jumping','aggression']],['Goleiro',['gkdiving','gkhandling','gkkicking','gkpositioning','gkreflexes']]];
const labels=['Aceleração','Velocidade','Agilidade','Reações','Equilíbrio','Força do chute','Finalização','Chutes de longe','Voleios','Pênaltis','Visão','Cruzamento','Passe curto','Passe longo','Curva','Faltas','Controle de bola','Drible','Força','Fôlego','Impulsão','Agressividade','Interceptação','Posicionamento','Marcação','Desarme','Carrinho','Cabeceio','Elasticidade','Manejo','Reposição','Posicionamento','Reflexos','Potencial'];
const keys=['acceleration','sprintspeed','agility','reactions','balance','shotpower','finishing','longshots','volleys','penalties','vision','crossing','shortpassing','longpassing','curve','freekickaccuracy','ballcontrol','dribbling','strength','stamina','jumping','aggression','interceptions','positioning','marking','standingtackle','slidingtackle','headingaccuracy','gkdiving','gkhandling','gkkicking','gkpositioning','gkreflexes','potential'];
let context={},player=null,tab=0,portrait=false,pose=101,busy=false,renderRevision=0;
const tabs=['Resumo','Desempenho','Atributos'];
const num=v=>v!=null&&v>=0?esc(v):'—',fact=(label,value)=>`<div><span>${esc(label)}</span><strong>${esc(value??'—')}</strong></div>`;
function competition(){const rows=[...(player.competitions||[])];for(const entry of context.detail?.competitions||[]){if(!rows.some(row=>row.root===entry.root))rows.push({...entry,games:0,goals:0,assists:0,cleanSheets:0,average:null,recorded:false});}
 const cell=(r,k)=>num(r[k]),rating=r=>r.average!=null&&r.average>=0?Number(r.average).toFixed(1):'—';const total={games:0,goals:0,assists:0,cleanSheets:0};rows.forEach(r=>Object.keys(total).forEach(k=>total[k]=total[k]==null||r[k]==null?null:total[k]+r[k]));
 return `<table class="profile-stats"><thead><tr><th>Competição</th><th>J</th><th>G</th><th>A</th><th>SG</th><th>Nota</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${r.asset?`<img src="icons/leagues/${r.asset}.webp" onerror="this.hidden=true" alt="">`:''}${esc(r.name||'Competição '+r.root)}${r.recorded===false?'<small class="stats-pending">Sem estatísticas registradas</small>':''}</th>${['games','goals','assists','cleanSheets'].map(k=>`<td>${cell(r,k)}</td>`).join('')}<td>${rating(r)}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma competição identificada nesta fonte do save.</td></tr>'}<tr class="total"><th>Total</th>${['games','goals','assists','cleanSheets'].map(k=>`<td>${cell(total,k)}</td>`).join('')}<td>—</td></tr></tbody></table>`;
}

function pitch(p){const points=[[.5,.91],[.5,.79],[.9,.66],[.84,.75],[.67,.75],[.5,.75],[.33,.75],[.16,.75],[.1,.66],[.67,.61],[.5,.61],[.33,.61],[.86,.48],[.67,.48],[.5,.48],[.33,.48],[.14,.48],[.67,.34],[.5,.34],[.33,.34],[.67,.23],[.5,.23],[.33,.23],[.86,.15],[.67,.1],[.5,.1],[.33,.1],[.14,.15]];const ids=[p.positionId,...(p.secondaryPositionIds||[])].filter((v,i,list)=>v!=null&&v>=0&&v<28&&list.indexOf(v)===i);return `<section class="position-field"><h3>Posições em campo</h3><svg viewBox="0 0 210 270" role="img" aria-label="${esc(p.position)} e posições secundárias"><rect x="8" y="8" width="194" height="254" rx="3"/><path d="M8 135h194M64 8v42h82V8M64 262v-42h82v42"/><circle cx="105" cy="135" r="29"/>${ids.map((id,i)=>`<g class="${i?'secondary':'primary'}"><circle cx="${15+points[id][0]*180}" cy="${15+points[id][1]*240}" r="11"/><text x="${15+points[id][0]*180}" y="${19+points[id][1]*240}">${i?'S':'P'}</text></g>`).join('')}</svg><small>P · Principal &nbsp; S · Secundária</small></section>`;}
function feet(p){const shape='M12 4C6 4 3 10 4 19l3 18c1 4 5 6 9 3 4-3 4-8 3-12l-2-11c3-5 1-13-5-13Z';return `<div class="preferred-feet" role="img" aria-label="Pé preferido: ${p.foot===1?'direito':p.foot===2?'esquerdo':'não informado'}"><svg viewBox="0 0 70 48"><path class="${p.foot===2?'preferred':''}" d="${shape}"/><path class="${p.foot===1?'preferred':''}" d="${shape}" transform="translate(65 0) scale(-1 1)"/></svg><small>${p.foot===1?'Direito':p.foot===2?'Esquerdo':'—'}</small></div>`;}
function content(){const p=player,a=p.attributes||{};
 if(tab===1)return `<h2>Desempenho na temporada</h2>${competition()}`;
 if(tab===2)return `<div class="profile-attribute-groups">${groups.filter(([n])=>n!=='Goleiro'||p.position==='GOL').map(([n,list])=>`<section><h3>${n}</h3>${list.map(k=>{const v=a[k],ok=v!=null&&v>=0&&v<=100;return `<div class="attribute"><span>${labels[keys.indexOf(k)]||k}</span><strong>${num(v)}</strong><div class="attribute-track"><i style="width:${ok?v:0}%;background:hsl(${ok?Math.max(0,Math.min(120,(v-40)*3)):0} 65% 52%)"></i></div></div>`;}).join('')}</section>`).join('')}</div>`;
 const summary=(p.position==='GOL'?[['Elasticidade',['gkdiving']],['Manejo',['gkhandling']],['Reposição',['gkkicking']],['Posição',['gkpositioning']],['Reflexos',['gkreflexes']],['Reações',['reactions']]]:groups.slice(0,6)).map(([n,list])=>{const vals=list.map(k=>a[k]).filter(v=>v!=null&&v>=0&&v<=99);return [n,vals.length===list.length?Math.round(vals.reduce((x,y)=>x+y,0)/vals.length):null];});
 return `<div class="profile-summary-ratings">${summary.map(([n,v])=>`<div><span>${n}</span><strong>${num(v)}</strong></div>`).join('')}</div><div class="profile-overview-body"><div class="profile-details">${fact('Clube',context.clubName)}${fact('Nacionalidade',p.nationName||'—')}${fact('Posições',[p.position,...(p.secondaryPositions||[])].filter(Boolean).join(' · '))}<div><span>Pé preferido</span>${feet(p)}</div>${fact('Potencial',p.potential>=0?p.potential:'—')}${fact('Salário semanal',p.weeklyWage!=null&&p.weeklyWage>=0?p.weeklyWage.toLocaleString('pt-BR'):'—')}${fact('No clube desde',p.joinDate||'—')}${fact('Nascimento',p.birthDate||'—')}${fact('Aposentadoria',p.retiring==null?'—':p.retiring?'Ao fim da temporada':'Não anunciada')}</div>${pitch(p)}</div>${window.FFSeasonCharts?.render(context.detail,p)||''}`;
}
function render(value){const serial=++renderRevision;context=value;const id=new URLSearchParams(location.search).get('id');player=(context.detail?.players||context.detail?.starters||[]).find(p=>String(p.id)===id);const body=document.getElementById('profile-body');if(!player){body.innerHTML='<div class="notice">Carregando o perfil do jogador…</div>';return;}
 const p=player;
 const oldActor=body.querySelector('.profile-actor'),owner=String(context.saveRevision||'')+':'+String(context.clubId)+':'+String(p.id);
 body.innerHTML=`<div class="profile-layout"><section class="profile-actor"><img class="profile-watermark" src="crests/${context.clubId}.webp" alt=""><canvas id="player-model-canvas" data-nav-item tabindex="0" hidden aria-label="Modelo 3D interativo do jogador"></canvas><div class="profile-model-status card-loading" role="status">Carregando modelo 3D…</div><div class="profile-bio"><div class="shirt-number">${p.number>0?p.number:''}</div>${fact('Idade',p.age!=null&&p.age>=0?p.age+' anos':'—')}${fact('Altura e peso',[p.height>0?p.height+' cm':null,p.weight>0?p.weight+' kg':null].filter(Boolean).join(' / ')||'—')}</div><div class="profile-actor-actions"><button data-profile-action="pose">Trocar pose</button></div></section><section class="profile-information"><nav class="profile-tabs">${tabs.map((name,i)=>`<button data-profile-tab="${i}" class="${tab===i?'active':''}">${name}</button>`).join('')}</nav><header class="profile-title"><img class="profile-title-face" src="${esc(p.portrait||`assets/players/${p.id}.webp`)}" alt="${esc(p.name)}" onerror="this.hidden=true"><div class="profile-name"><div class="muted">${esc(p.position)}${p.captain?' · CAPITÃO':''}</div><h1>${esc(p.name)}</h1><div class="profile-club"><img src="crests/${context.clubId}.webp" alt="">${esc(context.clubName)} · ${p.nationId?`<img class="nationality-flag" src="icons/countries/${p.nationId}.webp" onerror="this.hidden=true" alt="${esc(p.nationName||'')}">`:''}${esc(p.nationName||'')} · Camisa ${num(p.number)}</div></div><div class="profile-overall"><small>GERAL</small><strong>${num(p.overall)}</strong></div></header><div class="profile-content">${content()}</div></section></div>`;
 const newActor=body.querySelector('.profile-actor');if(oldActor?.dataset.owner===owner&&oldActor.dataset.portrait===String(portrait)){const oldBio=oldActor.querySelector('.profile-bio'),newBio=newActor.querySelector('.profile-bio');if(oldBio&&newBio)oldBio.innerHTML=newBio.innerHTML;newActor.replaceWith(oldActor);}else{newActor.dataset.owner=owner;newActor.dataset.portrait=String(portrait);}
 if(!portrait&&window.FFPlayer3D&&window.FFClubData)ensureModel(p.id,pose);else FFPlayer3D?.dispose();
 body.querySelectorAll('[data-profile-tab]').forEach(b=>b.onclick=()=>{tab=Number(b.dataset.profileTab);render(context);window.dispatchEvent(new Event('ff-profile-render'));});
 body.querySelectorAll('[data-profile-action]').forEach(b=>b.onclick=()=>action(b.dataset.profileAction));
}
function ensureModel(id,poseId){const actor=document.querySelector('.profile-actor'),key=actor.dataset.owner+':'+poseId;if(actor.dataset.modelKey===key)return;actor.dataset.modelKey=key;return loadModel(id,poseId,actor,key);}
async function loadModel(id,poseId,actor=document.querySelector('.profile-actor'),key=actor.dataset.owner+':'+poseId){actor.dataset.modelKey=key;const status=actor.querySelector('.profile-model-status');try{const url=await FFClubData.model(context.clubId,id,poseId);if(!actor.isConnected||actor.dataset.modelKey!==key)return;await FFPlayer3D.load(actor.querySelector('#player-model-canvas'),url);if(actor.isConnected&&actor.dataset.modelKey===key&&status)status.hidden=true;}catch(error){if(actor.isConnected&&actor.dataset.modelKey===key&&status){status.hidden=false;status.classList.remove('card-loading');status.textContent='Não foi possível carregar o modelo 3D.';setTimeout(()=>{if(actor.dataset.modelKey===key)delete actor.dataset.modelKey;},5000);}console.error('Modelo interativo:',error);}}
function action(key){if(!player)return;if(key==='pose'){if(busy)return;const choices=Array.from({length:14},(_,i)=>101+i).filter(id=>id!==pose);pose=choices[Math.floor(Math.random()*choices.length)];busy=true;const button=document.querySelector('[data-profile-action=pose]');if(button){button.textContent='Atualizando pose…';button.disabled=true;}loadModel(player.id,pose).finally(()=>{busy=false;if(button){button.disabled=false;button.textContent='Trocar pose';}window.dispatchEvent(new Event('ff-profile-render'));});}else if(key==='previous'||key==='next'){tab=(tab+(key==='next'?1:2))%3;render(context);}window.dispatchEvent(new Event('ff-profile-render'));}
window.FFPlayerProfile={render,action};
})();
