(() => {
let roomCamera=null,roomInitial=null,roomResetHeld=false,roomWalls=[],roomStep=0,roomBob=0;
let canvas=null,gl=null,program=null,meshes=[],textures=[],bounds=null,yaw=0,pitch=0,roll=0,zoom=1,panX=0,panY=0,revision=0,active='',frameId=0,previousTime=0,resize=null,lastDrawState='';
let shadowProgram=null,shadowTexture=null,shadowBuffer=null,lightMatrix=null,roomLights=[];
// Only generated assets are cached; career APIs always read the current save.
let assetCache=null,assetCacheName='';
async function selectAssetCache(url){const match=url.match(/interactive-models\/([a-f0-9]{16})-/);if(!match||!window.caches)return;const prefix='ff-3d-v1-'+(window.chrome?.webview?'game-':'preview-'),name=prefix+match[1];if(name===assetCacheName)return;assetCacheName=name;try{for(const key of await caches.keys())if(key.startsWith(prefix)&&key!==name)await caches.delete(key);assetCache=await caches.open(name);}catch{assetCache=null;}}
async function assetFetch(url){const key=String(url),cache=assetCache,name=assetCacheName;if(cache){const hit=await cache.match(key);if(hit)return hit;}const response=await fetch(key);if(!response.ok)throw new Error('Arquivo 3D indisponível: '+response.status);if(cache&&name===assetCacheName){try{await cache.put(key,response.clone());}catch{}}return response;}
const held=new Set();window.addEventListener('keydown',e=>held.add(e.key.toLowerCase()));window.addEventListener('keyup',e=>held.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>held.clear());
const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;};
function roomForward(){const c=roomCamera;return [Math.sin(c.yaw)*Math.cos(c.pitch),Math.sin(c.pitch),-Math.cos(c.yaw)*Math.cos(c.pitch)];}
function roomOrbit(dx,dy){if(!roomCamera)return;roomCamera.yaw+=dx;roomCamera.pitch=Math.max(-1.15,Math.min(1.15,roomCamera.pitch+dy));}
function roomBlocked(x,z){if(x<bounds[0]+22||x>bounds[3]-22||z<bounds[2]+22||z>bounds[5]-22)return true;for(const [ax,az,bx,bz] of roomWalls){const dx=bx-ax,dz=bz-az,t=Math.max(0,Math.min(1,((x-ax)*dx+(z-az)*dz)/(dx*dx+dz*dz||1)));if((x-ax-t*dx)**2+(z-az-t*dz)**2<22**2)return true;}return false;}
function roomMove(right,up,forward){if(!roomCamera)return;const c=roomCamera,p=c.position,dx=Math.cos(c.yaw)*right+Math.sin(c.yaw)*forward,dz=Math.sin(c.yaw)*right-Math.cos(c.yaw)*forward;const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/10));const startX=p[0],startZ=p[2];for(let i=0;i<steps;i++){if(!roomBlocked(p[0]+dx/steps,p[2]))p[0]+=dx/steps;if(!roomBlocked(p[0],p[2]+dz/steps))p[2]+=dz/steps;}const moved=Math.hypot(p[0]-startX,p[2]-startZ);roomStep+=moved*.055;roomBob=Math.min(1,roomBob+moved*.12);}
function roomDolly(amount){if(roomCamera)roomCamera.fov=Math.max(40,Math.min(85,roomCamera.fov+amount*35));}
function roomCollision(meta,data){roomWalls=[];const eye=roomCamera.position[1];for(const part of meta.parts){const verts=new DataView(data,part.vertexOffset,part.vertexCount*32),indices=new Uint32Array(data,part.indexOffset,part.indexCount);for(let i=0;i+2<indices.length;i+=3){const v=[indices[i],indices[i+1],indices[i+2]].map(n=>[verts.getFloat32(n*32,true),verts.getFloat32(n*32+4,true),verts.getFloat32(n*32+8,true)]);for(const height of [eye,eye-75]){const points=[];for(let j=0;j<3;j++){const a=v[j],b=v[(j+1)%3];if((a[1]<=height&&b[1]>height)||(b[1]<=height&&a[1]>height)){const t=(height-a[1])/(b[1]-a[1]);points.push([a[0]+t*(b[0]-a[0]),a[2]+t*(b[2]-a[2])]);}}if(points.length===2)roomWalls.push([...points[0],...points[1]]);}}}}
function init(target){if(canvas===target&&gl)return;dispose();canvas=target;gl=canvas.getContext('webgl2',{alpha:true,antialias:true});if(!gl)throw new Error('WebGL2 indisponível');program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`#version 300 es
layout(location=0) in vec3 position;layout(location=1) in vec3 normal;layout(location=2) in vec2 uv;uniform mat4 camera;uniform mat4 rotation;uniform mat4 lightCamera;out vec3 n;out vec2 t;out vec4 lightPoint;out vec3 worldPosition;void main(){vec4 world=rotation*vec4(position,1.);gl_Position=camera*world;n=mat3(rotation)*normal;t=uv;lightPoint=lightCamera*world;worldPosition=world.xyz;}`));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`#version 300 es
precision highp float;in vec3 n;in vec2 t;in vec4 lightPoint;in vec3 worldPosition;uniform int lampCount;uniform vec3 lamps[12];uniform float lampRange;uniform sampler2D shadowMap;uniform bool useShadows;uniform sampler2D diffuse;uniform vec3 tint;uniform float alpha;uniform sampler2D coefficient;uniform int hairMode;uniform bool hasCoefficient;out vec4 color;void main(){vec4 c=texture(diffuse,t);float coverage=clamp(c.a*alpha,0.,1.);if(hairMode>0){coverage=hasCoefficient?texture(coefficient,t).r:coverage;if(hairMode==1){if(coverage<.65)discard;coverage=1.;}else{if(coverage<.08||coverage>=.65)discard;}}else if(c.a<.08)discard;vec3 normal=normalize(n);float incidence=max(0.,dot(normal,lampCount>0?normalize(lamps[0]-worldPosition):normalize(vec3(-.4,.7,1.))));float visibility=1.;vec3 q=lightPoint.xyz/lightPoint.w*.5+.5;if(useShadows&&all(greaterThan(q,vec3(0.)))&&all(lessThan(q,vec3(1.)))){visibility=0.;float bias=max(.0015,.004*(1.-incidence));for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++)visibility+=q.z-bias<=texture(shadowMap,q.xy+vec2(float(x),float(y))/1024.).r?1.:0.;visibility/=9.;}float ambient=.28+.12*max(0.,normal.y);vec3 lighting=vec3(.88,.94,1.)*ambient+vec3(1.,.96,.9)*incidence*.55*(.2+.8*visibility)+vec3(.1,.13,.16)*max(0.,dot(normal,normalize(vec3(.8,.1,-.6))));if(lampCount>0){lighting=vec3(.30,.31,.32);for(int i=0;i<12;i++){if(i>=lampCount)break;vec3 delta=lamps[i]-worldPosition;float distance=length(delta);vec3 direction=delta/max(distance,1.);float down=smoothstep(-.08,.28,direction.y);float falloff=1./(1.+pow(distance/lampRange,2.));float direct=max(0.,dot(normal,direction));lighting+=vec3(1.,.975,.93)*direct*down*falloff*.48*(i==0?.25+.75*visibility:1.);}if(max(tint.r,max(tint.g,tint.b))>1.15)lighting=vec3(1.);}color=vec4(c.rgb*tint*lighting,(hairMode>0?coverage:c.a*alpha));}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.useProgram(program);gl.uniform1i(gl.getUniformLocation(program,'diffuse'),0);
 canvas.ondblclick=()=>{if(canvas.dataset.readonly==='true')return;yaw=pitch=roll=panX=panY=0;zoom=1;if(roomInitial)roomCamera=JSON.parse(JSON.stringify(roomInitial));};let drag=null;canvas.onpointerdown=e=>{if(canvas.dataset.readonly==='true')return;canvas.focus({preventScroll:true});drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;if(roomCamera){const dx=e.clientX-drag[0],dy=e.clientY-drag[1];roomOrbit(dx*.0035,-dy*.0035);drag=[e.clientX,e.clientY];return;}if(e.ctrlKey&&canvas.dataset.framing==='room'){const h=bounds?Math.max(bounds[4]-bounds[1],1):1;panX+=(e.clientX-drag[0])*h*.003;panY-=(e.clientY-drag[1])*h*.003;drag=[e.clientX,e.clientY];return;}if(document.body.dataset.page==='player'){yaw+=(e.clientX-drag[0])*.012;panY-=(e.clientY-drag[1])*(bounds?bounds[4]-bounds[1]:180)*.003;pitch=roll=0;drag=[e.clientX,e.clientY];return;}if(e.shiftKey)roll+=(e.clientX-drag[0])*.012;else yaw+=(e.clientX-drag[0])*.012;pitch+=(e.clientY-drag[1])*.01;drag=[e.clientX,e.clientY];};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{if(canvas.dataset.readonly==='true')return;e.preventDefault();if(roomCamera){roomDolly(e.deltaY*.001);return;}if(canvas.dataset.focused!=='true'&&canvas.dataset.framing!=='room')return;zoom=Math.max(canvas.dataset.framing==='room'?.1:.65,Math.min(canvas.dataset.framing==='room'?30:2.8,zoom*Math.exp(-e.deltaY*.001)));};
 resize=new ResizeObserver(()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,1.5,1600/Math.max(1,r.width),1000/Math.max(1,r.height));canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));});resize.observe(canvas);frameId=requestAnimationFrame(frame);
}
function multiply(a,b){const c=new Float32Array(16);for(let i=0;i<4;i++)for(let j=0;j<4;j++)for(let k=0;k<4;k++)c[i*4+j]+=a[k*4+j]*b[i*4+k];return c;}
function frame(time){frameId=requestAnimationFrame(frame);const dt=Math.min(.05,(time-previousTime)/1000||0);previousTime=time;roomBob*=Math.exp(-dt*8);if(!gl||!bounds)return;
 const pad=[...(navigator.getGamepads?.()||[])].find(p=>p?.connected);if(pad&&!roomCamera&&(document.body.dataset.page==='player'||document.body.dataset.page==='scene')&&canvas.isConnected&&canvas.getClientRects().length&&(document.body.dataset.page==='scene'||pad.buttons[3]?.pressed)){const x=pad.axes[2]||0,y=pad.axes[3]||0,h=bounds[4]-bounds[1];if(Math.abs(pad.axes[0]||0)>.16)panX+=pad.axes[0]*dt*h*.6;if(Math.abs(pad.axes[1]||0)>.16)panY-=pad.axes[1]*dt*h*.6;if(document.body.dataset.page==='player'){if(Math.abs(x)>.16)yaw+=x*dt*2.8;if(Math.abs(y)>.16)panY-=y*dt*h*.6;pitch=roll=0;}else{if(Math.abs(x)>.16){if(pad.buttons[11]?.pressed)roll+=x*dt*2.8;else yaw+=x*dt*2.8;}if(Math.abs(y)>.16)pitch-=y*dt*2.8;}zoom=Math.max(canvas.dataset.framing==='room'?.1:.65,Math.min(canvas.dataset.framing==='room'?30:2.8,zoom*Math.exp(((pad.buttons[7]?.value||0)-(pad.buttons[6]?.value||0))*dt)));}
 if(roomCamera){const reset=held.has('r')||!!pad?.buttons[3]?.pressed;if(reset&&!roomResetHeld&&roomInitial)roomCamera=JSON.parse(JSON.stringify(roomInitial));roomResetHeld=reset;const dead=v=>Math.abs(v)>.2?(Math.abs(v)-.2)/.8*Math.sign(v):0;if(pad){roomOrbit(dead(pad.axes[2]||0)*dt*1.05,-dead(pad.axes[3]||0)*dt*.8);roomMove(dead(pad.axes[0]||0)*dt*(held.has('shift')?360:240),0,-dead(pad.axes[1]||0)*dt*(held.has('shift')?360:240));roomDolly(((pad.buttons[6]?.value||0)-(pad.buttons[7]?.value||0))*dt*.7);}roomMove(((held.has('d')?1:0)-(held.has('a')?1:0))*dt*(held.has('shift')?360:240),((held.has('e')?1:0)-(held.has('q')?1:0))*dt*(held.has('shift')?360:240),((held.has('w')?1:0)-(held.has('s')?1:0))*dt*(held.has('shift')?360:240));}

 const state=[revision,canvas.width,canvas.height,yaw,pitch,roll,zoom,panX,panY,...(roomCamera?[...roomCamera.position,roomCamera.yaw,roomCamera.pitch,roomCamera.fov,roomBob>.001?roomStep:0,roomBob>.001?roomBob:0]:[])].join(':');if(state===lastDrawState)return;lastDrawState=state;
 const height=bounds[4]-bounds[1],cx=(bounds[0]+bounds[3])/2,cy=canvas.dataset.framing==='face'?bounds[1]+height*.91:(bounds[1]+bounds[4])/2,cz=(bounds[2]+bounds[5])/2,aspect=canvas.width/canvas.height,distance=(canvas.dataset.framing==='face'?height*.38:['group','room'].includes(canvas.dataset.framing)?Math.max(height*1.45,(bounds[3]-bounds[0])/aspect*1.3,canvas.dataset.framing==='room'?(bounds[5]-bounds[2])*1.3:0):height*1.45)/zoom,f=1/Math.tan(.45),near=.1,far=height*30;
 let projection=new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),view=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,panX,panY,-distance,1]);
 const sy=Math.sin(yaw),co=Math.cos(yaw),sp=Math.sin(pitch),cp=Math.cos(pitch),rotation=multiply(new Float32Array([co,0,-sy,0,0,1,0,0,sy,0,co,0,0,0,0,1]),new Float32Array([1,0,0,0,0,cp,sp,0,0,-sp,cp,0,0,0,0,1]));const translate=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,-cx,-cy,-cz,1]);
 if(roomCamera){const c=roomCamera,fw=roomForward(),r=[Math.cos(c.yaw),0,Math.sin(c.yaw)],u=[-Math.sin(c.yaw)*Math.sin(c.pitch),Math.cos(c.pitch),Math.cos(c.yaw)*Math.sin(c.pitch)],p=[c.position[0]+Math.cos(c.yaw)*Math.sin(roomStep)*roomBob*.35,c.position[1]+Math.sin(roomStep*2)*roomBob*1.2,c.position[2]+Math.sin(c.yaw)*Math.sin(roomStep)*roomBob*.35],dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0),fov=1/Math.tan(c.fov*Math.PI/360),n=2,z=60000;projection=new Float32Array([fov/aspect,0,0,0,0,fov,0,0,0,0,(z+n)/(n-z),-1,0,0,2*z*n/(n-z),0]);view.set([r[0],u[0],-fw[0],0,r[1],u[1],-fw[1],0,r[2],u[2],-fw[2],0,-dot(r,p),-dot(u,p),dot(fw,p),1]);}
 gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,shadowTexture||textures.white);gl.activeTexture(gl.TEXTURE0);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniform1i(gl.getUniformLocation(program,'useShadows'),!!lightMatrix);gl.uniform1i(gl.getUniformLocation(program,'lampCount'),roomLights.length);gl.uniform1f(gl.getUniformLocation(program,'lampRange'),active.includes('-303-')?650:260);if(roomLights.length)gl.uniform3fv(gl.getUniformLocation(program,'lamps[0]'),new Float32Array(roomLights.flat()));gl.uniform1i(gl.getUniformLocation(program,'shadowMap'),2);gl.uniformMatrix4fv(gl.getUniformLocation(program,'lightCamera'),false,lightMatrix||new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]));gl.uniformMatrix4fv(gl.getUniformLocation(program,'camera'),false,multiply(projection,view));gl.uniformMatrix4fv(gl.getUniformLocation(program,'rotation'),false,roomCamera?new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]):multiply(multiply(new Float32Array([Math.cos(roll),Math.sin(roll),0,0,-Math.sin(roll),Math.cos(roll),0,0,0,0,1,0,0,0,0,1]),rotation),translate));
 for(let pass=0;pass<3;pass++)for(const m of meshes){if(pass===0&&(m.hair||m.blend)||pass===1&&!m.hair||pass===2&&!(m.hair||m.blend))continue;gl.uniform1i(gl.getUniformLocation(program,'hairMode'),m.hair?(pass===1?1:2):0);gl.uniform1i(gl.getUniformLocation(program,'hasCoefficient'),m.hairCoefficient>=0);gl.uniform1i(gl.getUniformLocation(program,'coefficient'),1);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,textures[m.hairCoefficient]||textures.white);gl.activeTexture(gl.TEXTURE0);gl.bindVertexArray(m.vao);gl.bindTexture(gl.TEXTURE_2D,textures[m.texture]||textures.white);gl.uniform3fv(gl.getUniformLocation(program,'tint'),m.texture>=0?m.tint:m.color);gl.uniform1f(gl.getUniformLocation(program,'alpha'),m.alpha||1);if(pass===2){gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);}else{gl.disable(gl.BLEND);gl.depthMask(true);}gl.drawElements(gl.TRIANGLES,m.indexCount,gl.UNSIGNED_INT,0);}gl.depthMask(true);
}
function prepareShadows(){lightMatrix=null;roomLights=[];if(!roomCamera)return;
const outdoor=active.includes('-304-'),gym=active.includes('-303-'),press=active.includes('-301-');
if(!outdoor){const xs=gym?[-800,0,800]:press?[-300,0,300]:[-320,0,320],zs=gym?[-1450,-650]:press?[-350,35,420,820]:[-350,115,580],height=gym?689:307;for(const x of xs)for(const z of zs)roomLights.push([x,height,z]);if(gym)for(let i=0;i<3;i++)roomLights.push([-620+i*550,325,-1460]);const key=gym?[0,689,-650]:[0,307,press?35:115];roomLights.sort((a,b)=>Math.hypot(...a.map((v,i)=>v-key[i]))-Math.hypot(...b.map((v,i)=>v-key[i])));}
const dir=[-.312,.546,.781],radius=7000,center=roomCamera.position.map((v,i)=>v+roomForward()[i]*650);center[1]=bounds[1]+100;
const eye=outdoor?center.map((v,i)=>v+dir[i]*radius*2):roomLights[0],target=outdoor?center:[eye[0],eye[1]-1,eye[2]],normalize=v=>{const l=Math.hypot(...v);return v.map(x=>x/l);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],z=normalize(eye.map((v,i)=>v-target[i])),x=normalize(cross(outdoor?[0,1,0]:[0,0,-1],z)),y=cross(z,x),dot=(a,b)=>a.reduce((n,v,i)=>n+v*b[i],0),view=new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]),near=5,far=outdoor?radius*5:3000,f=1/Math.tan(145*Math.PI/360),projection=outdoor?new Float32Array([1/radius,0,0,0,0,1/radius,0,0,0,0,-2/(far-near),0,0,0,-(far+near)/(far-near),1]):new Float32Array([f,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);lightMatrix=multiply(projection,view);
if(!shadowProgram){shadowProgram=gl.createProgram();gl.attachShader(shadowProgram,shader(gl.VERTEX_SHADER,`#version 300 es
layout(location=0) in vec3 position;layout(location=2) in vec2 uv;uniform mat4 lightCamera;out vec2 t;out float height;void main(){gl_Position=lightCamera*vec4(position,1.);t=uv;height=position.y;}`));gl.attachShader(shadowProgram,shader(gl.FRAGMENT_SHADER,`#version 300 es
precision highp float;in vec2 t;in float height;uniform sampler2D diffuse;uniform float ceiling;void main(){if(texture(diffuse,t).a<.4)discard;}`));gl.linkProgram(shadowProgram);if(!gl.getProgramParameter(shadowProgram,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(shadowProgram));shadowTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,shadowTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,1024,1024,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);for(const pname of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,pname,gl.NEAREST);for(const pname of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,pname,gl.CLAMP_TO_EDGE);shadowBuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,shadowBuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,shadowTexture,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);}
gl.bindFramebuffer(gl.FRAMEBUFFER,shadowBuffer);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE){lightMatrix=null;gl.bindFramebuffer(gl.FRAMEBUFFER,null);return;}gl.viewport(0,0,1024,1024);gl.depthMask(true);gl.disable(gl.BLEND);gl.clear(gl.DEPTH_BUFFER_BIT);gl.useProgram(shadowProgram);gl.uniformMatrix4fv(gl.getUniformLocation(shadowProgram,'lightCamera'),false,lightMatrix);gl.uniform1f(gl.getUniformLocation(shadowProgram,'ceiling'),outdoor?1e8:bounds[1]+280);gl.uniform1i(gl.getUniformLocation(shadowProgram,'diffuse'),0);gl.activeTexture(gl.TEXTURE0);for(const m of meshes){if(m.blend||m.hair)continue;gl.bindTexture(gl.TEXTURE_2D,textures[m.texture]||textures.white);gl.bindVertexArray(m.vao);gl.drawElements(gl.TRIANGLES,m.indexCount,gl.UNSIGNED_INT,0);}gl.bindFramebuffer(gl.FRAMEBUFFER,null);lastDrawState='';}
async function load(target,url){const started=performance.now(),timings={};init(target);if(active===url&&meshes.length)return;active=url;const token=++revision;await selectAssetCache(url);if(token!==revision)return;const meta=await (await assetFetch(url)).json(),base=new URL('.',url),data=await (await assetFetch(new URL(meta.buffer,base))).arrayBuffer();timings.fetchMs=performance.now()-started;if(token!==revision)return;for(const m of meshes){gl.deleteVertexArray(m.vao);gl.deleteBuffer(m.vbo);gl.deleteBuffer(m.ibo);}meshes=[];for(const tex of textures)if(tex)gl.deleteTexture(tex);textures=[];
 const texture=()=>{const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);return tex;};textures.white=texture();gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([255,255,255,255]));
 const decodeStarted=performance.now();const decoded=new Array(meta.textures.length);let nextTexture=0;await Promise.all(Array.from({length:Math.min(4,meta.textures.length)},async()=>{while(nextTexture<meta.textures.length){const index=nextTexture++,path=meta.textures[index];if(!path)continue;const blob=await(await assetFetch(new URL(path,base))).blob();decoded[index]=await createImageBitmap(blob);}}));if(token!==revision){decoded.forEach(bitmap=>bitmap?.close());return;}timings.decodeMs=performance.now()-decodeStarted;let uploadSlice=performance.now(),uploadStarted=uploadSlice;for(const bitmap of decoded){if(performance.now()-uploadSlice>8){await new Promise(requestAnimationFrame);if(token!==revision){decoded.forEach(b=>b?.close());return;}uploadSlice=performance.now();}if(!bitmap){textures.push(null);continue;}const tex=texture();gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,bitmap);bitmap.close();textures.push(tex);}
 for(const part of meta.parts){if(performance.now()-uploadSlice>8){await new Promise(requestAnimationFrame);if(token!==revision)return;uploadSlice=performance.now();}if(!part.indexCount||!part.vertexCount)continue;const vao=gl.createVertexArray(),vbo=gl.createBuffer(),ibo=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,new Uint8Array(data,part.vertexOffset,part.vertexCount*32),gl.STATIC_DRAW);for(const [name,size,offset] of [['position',3,0],['normal',3,12],['uv',2,24]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,32,offset);}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ibo);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint8Array(data,part.indexOffset,part.indexCount*4),gl.STATIC_DRAW);meshes.push({...part,vao,vbo,ibo});}meshes.sort((a,b)=>Number(a.blend)-Number(b.blend));bounds=meta.bounds;if(canvas.dataset.framing==='room'&&meta.camera){roomCamera={...meta.camera,distance:650};const fw=roomForward();roomCamera.target=roomCamera.position.map((v,i)=>v+fw[i]*roomCamera.distance);roomCamera.position[1]=Math.max(bounds[1]+165,Math.min(roomCamera.position[1],bounds[1]+180));roomCamera.pitch=0;roomInitial=JSON.parse(JSON.stringify(roomCamera));roomCollision(meta,data);}prepareShadows();timings.uploadMs=performance.now()-uploadStarted;timings.totalMs=performance.now()-started;console.info('FF 3D performance',JSON.stringify({...timings,parts:meshes.length,textures:meta.textures.length,geometryBytes:data.byteLength}));canvas.hidden=false;const fallback=document.getElementById('player-render');if(fallback)fallback.hidden=true;window.dispatchEvent(new Event('ff-profile-render'));
}
function dispose(){cancelAnimationFrame(frameId);resize?.disconnect();if(gl){for(const m of meshes){gl.deleteVertexArray(m.vao);gl.deleteBuffer(m.vbo);gl.deleteBuffer(m.ibo);}for(const t of textures)if(t)gl.deleteTexture(t);if(textures.white)gl.deleteTexture(textures.white);if(program)gl.deleteProgram(program);if(shadowProgram)gl.deleteProgram(shadowProgram);if(shadowTexture)gl.deleteTexture(shadowTexture);if(shadowBuffer)gl.deleteFramebuffer(shadowBuffer);}shadowProgram=shadowTexture=shadowBuffer=lightMatrix=null;roomLights=[];meshes=[];textures=[];bounds=null;roomCamera=roomInitial=null;roomWalls=[];active='';lastDrawState='';gl=null;canvas=null;revision++;}
window.FFPlayer3D={load,dispose};
})();
