(() => {
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const valid=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
 function ring(value,label,note){const ok=valid(value),pct=ok?Math.max(0,Math.min(100,value)):0;return `<div class="season-ring-item"><div class="season-ring" style="--rate:${pct}%" role="img" aria-label="${esc(label)}: ${ok?pct.toFixed(0)+' por cento':'sem dados'}"><strong>${ok?pct.toFixed(0)+'%':'—'}</strong></div><b>${esc(label)}</b><small>${esc(note)}</small></div>`;}
 function bars(rows){const max=Math.max(1,...rows.map(r=>valid(r[1])?r[1]:0));return `<div class="season-bars">${rows.map(([label,value,color])=>`<div class="season-bar-row"><span>${esc(label)}</span><div class="season-bar-track"><i style="width:${valid(value)?value/max*100:0}%;background:${color}"></i></div><strong>${valid(value)?value:'—'}</strong></div>`).join('')}</div>`;}
 function record(label,stats){const ok=stats&&['games','wins','draws','losses'].every(k=>valid(stats[k]))&&stats.recorded!==false;const s=ok?stats:{};const rate=ok?(s.games>0?(s.wins*3+s.draws)/(s.games*3)*100:0):null;return `<section class="season-chart-panel"><h3>${esc(label)}</h3><div class="season-chart-body">${ring(rate,'Aproveitamento','Pontos / pontos possíveis')}${bars([['Vitórias',s.wins,'#57c995'],['Empates',s.draws,'#e1b958'],['Derrotas',s.losses,'#e2747c']])}</div><small class="season-chart-note">${ok?s.games+' jogos':'Sem resultados registrados no save'}</small></section>`;}
 function render(detail,player){const d=detail||{},s=d.season;let html=`<section class="season-charts"><h2>Desempenho do clube</h2><div class="season-chart-grid">${record('Geral',s)}${record('Mandante',s?.home||d.homeSeason)}${record('Visitante',s?.away||d.awaySeason)}</div>`;
 if(player){const rows=(player.competitions||[]).filter(r=>r.recorded!==false),sum=k=>rows.length&&rows.every(r=>valid(r[k]))?rows.reduce((v,r)=>v+r[k],0):null;const games=sum('games'),rate=valid(games)&&valid(s?.games)&&s.games>0&&games<=s.games?games/s.games*100:null;html+=`<section class="season-chart-panel individual-chart"><h3>Participação individual na temporada</h3><div class="season-chart-body">${ring(rate,'Presença em jogos','Jogos do jogador / jogos do clube')}${bars([['Jogos',games,'#59a9e8'],['Gols',sum('goals'),'#57c995'],['Assistências',sum('assists'),'#c399ec']])}</div><small class="season-chart-note">${rate==null?'Percentual disponível quando jogador e clube tiverem resultados da mesma temporada.':'Participação em jogos, sem atribuir os resultados do clube ao jogador.'}</small></section>`;}
 return html+'</section>';}
 function table(rows){return `<div class="club-competition-table"><table><thead><tr><th>Competição</th><th>J</th><th>V</th><th>E</th><th>D</th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><th>${esc(r.name||'Competição')}${r.recorded===false?'<small>Sem estatísticas registradas</small>':''}</th>${['games','wins','draws','losses'].map(k=>`<td>${esc(r[k]??0)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="5">Nenhuma competição identificada no save.</td></tr>'}</tbody></table></div>`;}
 window.FFSeasonCharts={render,table};
})();
