#include "viewer_animation.h"
#include "viewer_team.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <map>
#include <set>
#include <stdexcept>
using namespace DirectX;
namespace studio {
thread_local std::vector<AnimationJoint>animation_frame;
thread_local std::map<int,float>manual_floors;
thread_local bool capture_manual_floor=false;
static XMFLOAT4X4 matrix(const ufbx_matrix&m){XMFLOAT4X4 out(float(m.m00),float(m.m10),float(m.m20),0,float(m.m01),float(m.m11),float(m.m21),0,float(m.m02),float(m.m12),float(m.m22),0,float(m.m03),float(m.m13),float(m.m23),1);return out;}
static XMMATRIX orientation(const XMFLOAT4X4&m){auto out=XMLoadFloat4x4(&m);for(int i=0;i<3;++i)out.r[i]=XMVector3Normalize(out.r[i]);out.r[3]=XMVectorSet(0,0,0,1);return out;}
void FbxClip::load(const fs::path&path){
    auto length=fs::file_size(path);if(length>128*1024*1024)throw std::runtime_error("FBX excede 128 MB");std::ifstream in(path,std::ios::binary);std::vector<char>data(size_t(length),0);if(!in.read(data.data(),data.size()))throw std::runtime_error("Não foi possível ler o FBX");
    ufbx_load_opts opts={};opts.ignore_geometry=true;opts.ignore_embedded=true;opts.load_external_files=false;opts.target_axes=ufbx_axes_right_handed_y_up;opts.target_unit_meters=.01;opts.temp_allocator.memory_limit=256*1024*1024;opts.result_allocator.memory_limit=256*1024*1024;ufbx_error error={};auto*loaded=ufbx_load_memory(data.data(),data.size(),&opts,&error);if(!loaded){char text[512];ufbx_format_error(text,sizeof(text),&error);throw std::runtime_error(std::string("FBX inválido: ")+text);}std::shared_ptr<ufbx_scene>next(loaded,ufbx_free_scene);if(loaded->nodes.count>10000)throw std::runtime_error("FBX excede o limite de nós");scene_=std::move(next);file=path;names.clear();takes.clear();for(auto*n:scene_->nodes)names.emplace_back(n->name.data,n->name.length);for(auto*stack:scene_->anim_stacks)takes.emplace_back(stack->name.data,stack->name.length);select_take(0);
}
void FbxClip::select_take(int index){take=std::clamp(index,0,std::max(0,int(takes.size())-1));if(!scene_)return;if(scene_->anim_stacks.count){auto*s=scene_->anim_stacks[take];start=s->time_begin;duration=std::max(0.0,s->time_end-start);}else{start=scene_->anim->time_begin;duration=std::max(0.0,scene_->anim->time_end-start);}if(duration>600)throw std::runtime_error("Animação excede dez minutos");}
std::vector<ImportedBone>FbxClip::sample(double time)const{if(!scene_)return {};ufbx_error error={};auto*anim=scene_->anim_stacks.count?scene_->anim_stacks[take]->anim:scene_->anim;auto*evaluated=ufbx_evaluate_scene(scene_.get(),anim,start+std::clamp(time,0.0,duration),nullptr,&error);if(!evaluated)throw std::runtime_error("Não foi possível avaliar o quadro FBX");std::shared_ptr<ufbx_scene>frame(evaluated,ufbx_free_scene);std::map<uint32_t,ufbx_matrix>bind;for(auto*p:scene_->poses)if(p->is_bind_pose)for(auto&bone:p->bone_poses)bind[bone.bone_node->typed_id]=bone.bone_to_world;
    std::vector<ImportedBone>out;out.reserve(scene_->nodes.count);for(auto*n:scene_->nodes){auto*a=frame->nodes[n->typed_id];auto rest=bind.count(n->typed_id)?bind[n->typed_id]:n->node_to_world;auto current=a->node_to_world;ImportedBone bone;bone.name.assign(n->name.data,n->name.length);bone.bind=matrix(rest);bone.animated=matrix(current);bone.bind_position={bone.bind._41,bone.bind._42,bone.bind._43};bone.position={bone.animated._41,bone.animated._42,bone.animated._43};bone.parent=n->parent?int(n->parent->typed_id):-1;out.push_back(std::move(bone));}return out;
}
static std::string normalized(std::string s){auto colon=s.find_last_of(':');if(colon!=s.npos)s=s.substr(colon+1);s.erase(std::remove_if(s.begin(),s.end(),[](unsigned char c){return !isalnum(c);}),s.end());for(char&c:s)if(c>='A'&&c<='Z')c+=32;return s;}
std::vector<BoneMapping>auto_map(const std::vector<std::string>&targets,const std::vector<std::string>&sources){std::vector<BoneMapping>out;bool long_spine=std::find(targets.begin(),targets.end(),"Spine3")!=targets.end();for(auto&target:targets){if(target.rfind("RM_",0)==0||target=="Reference"||target=="Root"||target=="AITrajectory"||target=="Trajectory"||target=="End"||target=="Aux"||(long_spine&&target=="Spine1"))continue;std::string desired=target;if(long_spine&&target=="Spine2")desired="Spine1";else if(target=="Spine3")desired="Spine2";else if(target=="HeadEnd")desired="HeadTop_End";else if(target.size()>3&&target.compare(target.size()-3,3,"End")==0)continue;auto at=std::find_if(sources.begin(),sources.end(),[&](const std::string&s){return normalized(s)==normalized(desired);});if(at==sources.end())at=std::find_if(sources.begin(),sources.end(),[&](const std::string&s){return normalized(s)==normalized(target);});if(at!=sources.end())out.push_back({target,*at});}return out;}
static Vec3 subtract(Vec3 a,Vec3 b){return {a.x-b.x,a.y-b.y,a.z-b.z};}
static std::string child_name(const std::string&name,bool long_spine){
    if(name=="Hips")return "Spine";if(name=="Spine")return long_spine?"Spine2":"Spine1";if(name=="Spine1")return "Spine2";if(name=="Spine2")return long_spine?"Spine3":"Neck";if(name=="Spine3")return "Neck";if(name=="Neck"||name=="Neck1")return "Head";if(name=="Head")return "HeadEnd";
    for(auto side:{std::string("Left"),std::string("Right")}){if(name==side+"Shoulder")return side+"Arm";if(name==side+"Arm")return side+"ForeArm";if(name==side+"ForeArm")return side+"Hand";if(name==side+"Hand")return side+"HandMiddle1";if(name==side+"UpLeg")return side+"Leg";if(name==side+"Leg")return side+"Foot";if(name==side+"Foot")return side+"ToeBase";if(name==side+"ToeBase")return side+"FootEnd";}
    if(name.find("Hand")!=name.npos&&!name.empty()){if(name.back()=='1'||name.back()=='2'){auto out=name;out.back()++;return out;}if(name.back()=='3')return name.substr(0,name.size()-1)+"End";}return {};
}
std::vector<AnimationJoint>retarget_frame(const std::vector<ImportedBone>&bones,const std::vector<BoneMapping>&mapping,bool root_motion){
    bool long_spine=std::any_of(mapping.begin(),mapping.end(),[](const auto&m){return m.target=="Spine3";});
    auto source_for=[&](const std::string&target){auto at=std::find_if(mapping.begin(),mapping.end(),[&](const auto&m){return m.target==target;});if(at!=mapping.end())return at->source;auto alias=target;if(target=="HeadEnd")alias="HeadTop_End";else if(target=="LeftFootEnd")alias="LeftToe_End";else if(target=="RightFootEnd")alias="RightToe_End";else if(target.size()>3&&target.substr(target.size()-3)=="End")alias=target.substr(0,target.size()-3)+"4";auto bone=std::find_if(bones.begin(),bones.end(),[&](const auto&b){return normalized(b.name)==normalized(alias);});return bone==bones.end()?std::string():bone->name;};
    auto find=[&](const std::string&name)->const ImportedBone*{auto at=std::find_if(bones.begin(),bones.end(),[&](const auto&b){return b.name==name;});return at==bones.end()?nullptr:&*at;};
    std::vector<AnimationJoint>out;for(auto&m:mapping){auto*at=find(m.source);if(!at||m.target.empty())continue;AnimationJoint j;j.name=m.target;j.bind=at->bind;j.animated=at->animated;j.child=child_name(j.name,long_spine);if(auto*c=find(source_for(j.child)))j.bind_direction=subtract(c->bind_position,at->bind_position);
        if(j.name=="LeftHand"||j.name=="RightHand"){auto side=j.name.substr(0,j.name.size()-4);auto*a=find(source_for(side+"HandIndex1")),*b=find(source_for(side+"HandPinky1"));if(a&&b)j.bind_secondary=subtract(b->bind_position,a->bind_position);}
        if(j.name=="Hips"){auto a=at->position,b=at->bind_position;float height=std::max(10.f,fabsf(b.y));j.root_translation={(root_motion?a.x-b.x:0)/height,(a.y-b.y)/height,(root_motion?a.z-b.z:0)/height};}out.push_back(j);
    }return out;
}
std::vector<JointEdit>sample_keys(const std::vector<Keyframe>&keys,float time){
    if(keys.empty())return {};
    auto after=std::upper_bound(keys.begin(),keys.end(),time,[](float t,const Keyframe&k){return t<k.time;});
    if(after==keys.begin())return keys.front().joints;if(after==keys.end())return keys.back().joints;
    auto&b=*after;auto&a=*(after-1);float t=(time-a.time)/std::max(.0001f,b.time-a.time);
    std::set<std::string>names;for(auto&j:a.joints)names.insert(j.name);for(auto&j:b.joints)names.insert(j.name);
    auto get=[](const auto&list,const std::string&name){auto it=std::find_if(list.begin(),list.end(),[&](const auto&j){return j.name==name;});return it==list.end()?JointEdit{name}:*it;};
    auto angle=[&](float x,float y){return x+std::remainder(y-x,360.f)*t;};auto linear=[&](float x,float y){return x+(y-x)*t;};
    std::vector<JointEdit>out;for(auto&name:names){auto x=get(a.joints,name),y=get(b.joints,name);out.push_back({name,{angle(x.rotation.x,y.rotation.x),angle(x.rotation.y,y.rotation.y),angle(x.rotation.z,y.rotation.z)},{linear(x.translation.x,y.translation.x),linear(x.translation.y,y.translation.y),linear(x.translation.z,y.translation.z)},linear(x.scale,y.scale)});}return out;
}
static XMVECTOR vector(Vec3 p){return XMVectorSet(p.x,p.y,p.z,0);}
static XMMATRIX align_direction(XMVECTOR a,XMVECTOR b){a=XMVector3Normalize(a);b=XMVector3Normalize(b);float dot=std::clamp(XMVectorGetX(XMVector3Dot(a,b)),-1.f,1.f);if(dot>.999999f)return XMMatrixIdentity();auto axis=XMVector3Cross(a,b);if(dot<-.999999f){axis=XMVector3Cross(a,XMVectorSet(0,1,0,0));if(XMVectorGetX(XMVector3LengthSq(axis))<.0001f)axis=XMVector3Cross(a,XMVectorSet(1,0,0,0));}return XMMatrixRotationAxis(XMVector3Normalize(axis),acosf(dot));}
static XMMATRIX anatomical_frame(XMVECTOR primary,XMVECTOR secondary){auto x=XMVector3Normalize(primary);auto y=XMVector3Normalize(secondary-x*XMVector3Dot(x,secondary));auto z=XMVector3Normalize(XMVector3Cross(x,y));XMMATRIX out;out.r[0]=x;out.r[1]=y;out.r[2]=z;out.r[3]=XMVectorSet(0,0,0,1);return out;}
void retarget(const fifa_player::Model&m,const std::vector<XMFLOAT4X4>&rest,std::vector<XMFLOAT4X4>&pose){if(animation_frame.empty()||!m.skeleton)return;auto&rig=*m.skeleton;pose=rest;
    auto index=[&](const std::string&name){auto at=std::find(rig.names.begin(),rig.names.end(),name);return at==rig.names.end()?rest.size():size_t(at-rig.names.begin());};
    auto position=[&](size_t i){return XMVectorSet(rest[i]._41,rest[i]._42,rest[i]._43,0);};
    std::vector<XMFLOAT4X4>desired(rest.size());std::vector<bool>mapped(rest.size(),false);
    for(size_t i=0;i<rig.names.size();++i){auto at=std::find_if(animation_frame.begin(),animation_frame.end(),[&](const auto&j){return j.name==rig.names[i];});if(at==animation_frame.end())continue;auto correction=XMMatrixIdentity();auto child=index(at->child);if(child==rest.size()&&(at->name=="LeftHand"||at->name=="RightHand"))child=index(at->name+"End");auto src=vector(at->bind_direction);
        if(child<rest.size()&&XMVectorGetX(XMVector3LengthSq(src))>.0001f){auto direction=position(child)-position(i);if(XMVectorGetX(XMVector3LengthSq(direction))>.0001f)correction=align_direction(direction,src);
            if(at->name=="LeftHand"||at->name=="RightHand"){auto side=at->name.substr(0,at->name.size()-4);auto a=index(side+"HandIndex1"),b=index(side+"HandPinky1");if(a<rest.size()&&b<rest.size()&&XMVectorGetX(XMVector3LengthSq(vector(at->bind_secondary)))>.0001f)correction=XMMatrixInverse(nullptr,anatomical_frame(direction,position(b)-position(a)))*anatomical_frame(src,vector(at->bind_secondary));}
        }
        XMStoreFloat4x4(&desired[i],orientation(rest[i])*correction*XMMatrixInverse(nullptr,orientation(at->bind))*orientation(at->animated));mapped[i]=true;
    }
    // Distribute FIFA's extra spine/neck links instead of duplicating Mixamo nodes.
    for(auto middle:{std::string("Spine1"),std::string("Neck1")}){size_t i=index(middle);if(i>=rest.size()||mapped[i])continue;auto lo=index(middle=="Spine1"?"Spine":"Neck"),hi=index(middle=="Spine1"?"Spine2":"Head");if(lo>=rest.size()||hi>=rest.size()||!mapped[lo]||!mapped[hi])continue;float total=XMVectorGetX(XMVector3Length(position(hi)-position(lo))),t=std::clamp(XMVectorGetX(XMVector3Length(position(i)-position(lo)))/std::max(.001f,total),0.f,1.f);auto a=XMMatrixInverse(nullptr,orientation(rest[lo]))*XMLoadFloat4x4(&desired[lo]);auto b=XMMatrixInverse(nullptr,orientation(rest[hi]))*XMLoadFloat4x4(&desired[hi]);auto blend=XMQuaternionSlerp(XMQuaternionRotationMatrix(a),XMQuaternionRotationMatrix(b),t);XMStoreFloat4x4(&desired[i],orientation(rest[i])*XMMatrixRotationQuaternion(blend));mapped[i]=true;}
    for(size_t joint=0;joint<rig.names.size();++joint){if(!mapped[joint])continue;auto delta=XMMatrixInverse(nullptr,orientation(pose[joint]))*XMLoadFloat4x4(&desired[joint]);auto pivot=pose[joint];auto transform=XMMatrixTranslation(-pivot._41,-pivot._42,-pivot._43)*delta*XMMatrixTranslation(pivot._41,pivot._42,pivot._43);
        for(size_t i=joint;i<pose.size();++i){size_t parent=i;while(parent!=joint&&rig.parents[parent]!=0xffff)parent=rig.parents[parent];if(parent==joint)XMStoreFloat4x4(&pose[i],XMLoadFloat4x4(&pose[i])*transform);}
        if(rig.names[joint]=="Hips"){auto at=std::find_if(animation_frame.begin(),animation_frame.end(),[](const auto&j){return j.name=="Hips";});float height=std::max(10.f,rest[joint]._42-m.bind_feet);auto d=at->root_translation;for(size_t i=joint;i<pose.size();++i){size_t parent=i;while(parent!=joint&&rig.parents[parent]!=0xffff)parent=rig.parents[parent];if(parent==joint){pose[i]._41+=d.x*height;pose[i]._42+=d.y*height;pose[i]._43+=d.z*height;}}}
    }
    // Match the support ankle's vertical motion without changing limb lengths.
    // If both feet rise in the FBX this retains the rise (not unconditional grounding).
    auto source_joint=[&](const char*name)->const AnimationJoint*{auto at=std::find_if(animation_frame.begin(),animation_frame.end(),[&](const auto&j){return j.name==name;});return at==animation_frame.end()?nullptr:&*at;};
    size_t left=index("LeftFoot"),right=index("RightFoot"),hips=index("Hips");auto*l=source_joint("LeftFoot"),*r=source_joint("RightFoot"),*h=source_joint("Hips");
    if(left<rest.size()&&right<rest.size()&&hips<rest.size()&&l&&r&&h){float ratio=(rest[hips]._42-m.bind_feet)/std::max(10.f,h->bind._42);float desired_height=std::min(rest[left]._42,rest[right]._42)+(std::min(l->animated._42,r->animated._42)-std::min(l->bind._42,r->bind._42))*ratio;float shift=desired_height-std::min(pose[left]._42,pose[right]._42);for(size_t i=hips;i<pose.size();++i){size_t parent=i;while(parent!=hips&&rig.parents[parent]!=0xffff)parent=rig.parents[parent];if(parent==hips)pose[i]._42+=shift;}}
}
float animation_floor(const fifa_player::Model&m,float computed){int id=model_actor_id(m);if(capture_manual_floor){manual_floors[id]=computed;return computed;}if(team_editing&&!team_apply_edits){auto*actor=actor_edit(team_edits,id);if(actor&&std::any_of(actor->joints.begin(),actor->joints.end(),[](const auto&e){return e.translation.x!=0||e.translation.y!=0||e.translation.z!=0;}))manual_floors[id]=computed;return computed;}bool selected=m.skeleton&&((pose_coach&&m.skeleton->names.size()==31)||(!pose_coach&&m.player_id==pose_player));if(!animation_frame.empty()&&selected)return m.bind_feet*m.bind_scale;auto at=manual_floors.find(id);return at==manual_floors.end()?computed:at->second;}
std::vector<NativeResource>native_resources(const fs::path&game){std::vector<NativeResource>out;auto animation_name=[](std::string s){for(char&c:s)if(c>='A'&&c<='Z')c+=32;auto ext=fs::path(s).extension().string();return ext==".cba"||ext==".cbac"||ext==".ant"||ext==".anim";};
    std::error_code ec;auto data=game/L"data";if(fs::exists(data))for(auto&entry:fs::recursive_directory_iterator(data,fs::directory_options::skip_permission_denied,ec)){if(entry.is_regular_file(ec)&&animation_name(utf8(entry.path().filename().wstring())))out.push_back({utf8(fs::relative(entry.path(),game).wstring()),"Arquivo solto",entry.file_size(ec)});if(out.size()>5000)break;}
    auto be32=[](const uint8_t*p){return uint32_t(p[0])<<24|uint32_t(p[1])<<16|uint32_t(p[2])<<8|p[3];};
    for(auto&entry:fs::directory_iterator(game)){if(entry.path().extension()!=L".big")continue;std::ifstream in(entry.path(),std::ios::binary);uint8_t header[16];if(!in.read(reinterpret_cast<char*>(header),16)||memcmp(header,"BIG4",4)&&memcmp(header,"BIGF",4))continue;size_t count=be32(header+8),length=be32(header+12);if(count>200000||length<16||length>32*1024*1024)continue;std::vector<uint8_t>index(length);in.seekg(0);if(!in.read(reinterpret_cast<char*>(index.data()),length))continue;size_t p=16;for(size_t i=0;i<count&&p+9<=index.size();++i){size_t bytes=be32(index.data()+p+4);p+=8;auto start=p;while(p<index.size()&&index[p]&&p-start<2048)++p;if(p>=index.size()||p-start>=2048)break;std::string name(index.begin()+start,index.begin()+p);++p;if(animation_name(name))out.push_back({name,utf8(entry.path().filename().wstring()),bytes});}}
    return out;
}
}
