#include "viewer_validation.h"
#include <wrl/client.h>
#include <fstream>
#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>
#include <imgui.h>
#include <ImGuizmo.h>
using namespace DirectX;
using namespace fifa_player;
using Microsoft::WRL::ComPtr;
namespace studio {
static float distance(Vec3 a,Vec3 b){return sqrtf((a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y)+(a.z-b.z)*(a.z-b.z));}
static void check(bool ok,const char*why){if(!ok)throw std::runtime_error(why);}
void test_gizmo_math(){
    for(auto angles:{Vec3{15,27,-33},Vec3{-46,125,76},Vec3{90,42,-12},Vec3{-90,-21,13}}){
        BonePoint bone;bone.point={12,85,-4};bone.units=1.1f;auto basis=XMMatrixRotationRollPitchYaw(.4f,-.7f,.3f);auto rotation=XMMatrixRotationRollPitchYaw(XMConvertToRadians(angles.x),XMConvertToRadians(angles.y),XMConvertToRadians(angles.z));XMStoreFloat4x4(&bone.frame,rotation*basis);bone.frame._41=12;bone.frame._42=85;bone.frame._43=-4;
        JointEdit old{"RightArm",angles};auto recovered=edit_from_gizmo(bone,old,bone.frame,false);XMFLOAT4X4 expected,actual;XMStoreFloat4x4(&expected,rotation);XMStoreFloat4x4(&actual,XMMatrixRotationRollPitchYaw(XMConvertToRadians(recovered.rotation.x),XMConvertToRadians(recovered.rotation.y),XMConvertToRadians(recovered.rotation.z)));for(int i=0;i<16;++i)check(fabsf((&expected._11)[i]-(&actual._11)[i])<.001f,"Gizmo: conversao de rotacao incorreta");
        auto next=bone.frame;auto move=XMVector3TransformNormal(XMVectorSet(3,-2,5,0),basis)*bone.units;next._41+=XMVectorGetX(move);next._42+=XMVectorGetY(move);next._43+=XMVectorGetZ(move);auto translated=edit_from_gizmo(bone,old,next,true);check(distance(translated.translation,{3,-2,5})<.001f,"Gizmo: movimento local/mundo incorreto");
    }
}
void test_gizmo_interaction(){
    auto*previous=ImGui::GetCurrentContext();auto*context=ImGui::CreateContext();struct Guard{ImGuiContext*context,*previous;~Guard(){ImGui::DestroyContext(context);ImGui::SetCurrentContext(previous);}}guard{context,previous};auto&io=ImGui::GetIO();io.IniFilename=nullptr;io.DisplaySize={1200,800};io.DeltaTime=1.f/60;unsigned char*pixels;int w,h;io.Fonts->GetTexDataAsRGBA32(&pixels,&w,&h);
    XMFLOAT4X4 view,projection,matrix;XMStoreFloat4x4(&view,XMMatrixLookAtRH(XMVectorSet(0,80,300,1),XMVectorSet(0,80,0,1),XMVectorSet(0,1,0,0)));XMStoreFloat4x4(&projection,XMMatrixPerspectiveFovRH(XM_PIDIV4,1000.f/700,.1f,100000));XMStoreFloat4x4(&matrix,XMMatrixTranslation(0,80,0));bool down=false;
    auto step=[&](ImVec2 mouse,bool pressed,ImGuizmo::OPERATION operation){io.AddMousePosEvent(mouse.x,mouse.y);if(pressed!=down){io.AddMouseButtonEvent(0,pressed);down=pressed;}ImGui::NewFrame();ImGuizmo::BeginFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(io.DisplaySize);ImGui::Begin("gizmo-test",nullptr,ImGuiWindowFlags_NoDecoration);ImGuizmo::SetDrawlist(ImGui::GetWindowDrawList());ImGuizmo::SetRect(100,50,1000,700);ImGuizmo::SetOrthographic(false);ImGuizmo::SetGizmoSizeClipSpace(.10f);ImGuizmo::Manipulate(&view._11,&projection._11,operation,ImGuizmo::WORLD,&matrix._11);bool over=ImGuizmo::IsOver(operation);ImGui::End();ImGui::Render();return over;};
    step({0,0},false,ImGuizmo::TRANSLATE_X);ImVec2 hit;bool found=false;for(float x=620;x<780;x+=2)if(step({x,400},false,ImGuizmo::TRANSLATE_X)){hit={x,400};found=true;break;}check(found,"Seta X nao pode ser selecionada");step(hit,true,ImGuizmo::TRANSLATE_X);step({hit.x+35,hit.y},true,ImGuizmo::TRANSLATE_X);step({hit.x+35,hit.y},false,ImGuizmo::TRANSLATE_X);check(matrix._41>1&&fabsf(matrix._42-80)<.01f&&fabsf(matrix._43)<.01f,"Arraste da seta nao move exclusivamente o eixo X");
    XMStoreFloat4x4(&matrix,XMMatrixTranslation(0,80,0));step({0,0},false,ImGuizmo::ROTATE_Z);float radius=0;found=false;for(float r=25;r<170;r+=2)if(step({600+r*.7071068f,400-r*.7071068f},false,ImGuizmo::ROTATE_Z)){hit={600+r*.7071068f,400-r*.7071068f};radius=r;found=true;break;}check(found,"Anel Z nao pode ser selecionado");step(hit,true,ImGuizmo::ROTATE_Z);step({600,400-radius},true,ImGuizmo::ROTATE_Z);step({600,400-radius},false,ImGuizmo::ROTATE_Z);check(fabsf(matrix._12)>.15f&&fabsf(matrix._42-80)<.01f,"Arraste do anel nao gira mantendo o pivo");
}
int verify_humanoid(const fs::path&root,const Settings&config,const fs::path&fbx){
    auto output=root/L"tests"/L"resultados";fs::create_directories(output);std::ofstream report(output/L"sad-idle-validacao.txt",std::ios::binary);
    try{
        test_gizmo_math();FbxClip clip;clip.load(fbx);auto source=clip.sample(0);check(clip.duration>0,"FBX sem animacao");Catalog catalog;catalog.load(wide(config.game));auto rows=catalog.rosters.at(1043);Assets assets(config.game);auto player=std::make_shared<Model>(assets.load(rows.front()));auto coach=assets.coach(rows.front());
        report<<"FBX: "<<utf8(fbx.wstring())<<"\nClip: "<<clip.takes.at(clip.take)<<"\nDuracao: "<<clip.duration<<" s; nos: "<<source.size()<<"\n";
        ComPtr<ID3D11Device>device;ComPtr<ID3D11DeviceContext>context;check(SUCCEEDED(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&device,nullptr,&context)),"D3D11 indisponivel");Renderer renderer;renderer.device(device.Get());
        for(int kind=0;kind<2;++kind){auto base=kind?coach.model:player;if(!base||!base->skeleton){report<<"Tecnico indisponivel\n";continue;}auto&rig=*base->skeleton;auto mapping=auto_map(rig.names,clip.names);auto label=kind?"tecnico":"jogador";
            report<<"\n"<<label<<": "<<rig.names.size()<<" ossos FIFA; "<<mapping.size()<<" correspondencias; escala="<<base->bind_scale<<"\n";
            std::ofstream map_report(output/(std::string("sad-idle-mapa-")+label+".tsv"),std::ios::binary);map_report<<"indice\tfifa\tpai\tmixamo\trestX\trestY\trestZ\n";
            std::vector<XMFLOAT4X4>rest(rig.names.size());for(size_t i=0;i<rest.size();++i){XMFLOAT4X4 inverse;std::copy(rig.inverse_bind[i].begin(),rig.inverse_bind[i].end(),&inverse._11);XMStoreFloat4x4(&rest[i],XMMatrixInverse(nullptr,XMLoadFloat4x4(&inverse)));auto at=std::find_if(mapping.begin(),mapping.end(),[&](const auto&m){return m.target==rig.names[i];});map_report<<i<<'\t'<<rig.names[i]<<'\t'<<(rig.parents[i]==0xffff?"-":rig.names[rig.parents[i]])<<'\t'<<(at==mapping.end()?"-":at->source)<<'\t'<<rest[i]._41*base->bind_scale<<'\t'<<rest[i]._42*base->bind_scale-base->bind_feet*base->bind_scale<<'\t'<<rest[i]._43*base->bind_scale<<'\n';}
            pose_coach=kind;pose_player=base->player_id;pose_edits.clear();std::vector<BonePoint>first;float max_error=0,max_movement=0,max_angle=0,max_support_error=0;int count=std::max(1,int(std::ceil(clip.duration*30)));
            for(int k=0;k<=count;++k){double time=clip.duration*k/count;animation_frame=retarget_frame(clip.sample(time),mapping,false);auto current=std::make_shared<Model>(*base);bool ok=kind?apply_coach_pose(*current,201):apply_presentation_pose(*current,false,nullptr,101);check(ok,"Nao aplicou animacao no modelo FIFA");auto points=pose_bones;check(points.size()==rig.names.size(),"Quantidade de ossos mudou durante a animacao");if(first.empty())first=points;
                for(size_t i=0;i<points.size();++i){auto p=points[i].point;check(std::isfinite(p.x)&&std::isfinite(p.y)&&std::isfinite(p.z),"Animacao produziu osso nao finito");max_movement=std::max(max_movement,distance(first[i].point,p));int parent=points[i].parent;if(parent>=0&&points[i].name!="Hips"){auto a=rest[i],b=rest[parent];float expected=distance({a._41,a._42,a._43},{b._41,b._42,b._43})*base->bind_scale;max_error=std::max(max_error,fabsf(distance(p,points[parent].point)-expected));}}
                for(auto&part:current->parts)for(auto&v:part.vertices)check(std::isfinite(v.position.x)&&std::isfinite(v.position.y)&&std::isfinite(v.position.z),"Animacao produziu malha nao finita");
                auto find_point=[&](const std::string&name)->const BonePoint*{auto at=std::find_if(points.begin(),points.end(),[&](const auto&p){return p.name==name;});return at==points.end()?nullptr:&*at;};
                for(auto&j:animation_frame){bool limb=j.name=="LeftArm"||j.name=="RightArm"||j.name=="LeftForeArm"||j.name=="RightForeArm"||j.name=="LeftUpLeg"||j.name=="RightUpLeg"||j.name=="LeftLeg"||j.name=="RightLeg"||j.name=="LeftFoot"||j.name=="RightFoot";if(!limb)continue;auto*a=find_point(j.name),*b=find_point(j.child);if(!a||!b)continue;auto expected=XMVector3Normalize(XMVector3TransformNormal(XMVectorSet(j.bind_direction.x,j.bind_direction.y,j.bind_direction.z,0),XMMatrixInverse(nullptr,bone_orientation(j.bind))*bone_orientation(j.animated)));auto actual=XMVector3Normalize(XMVectorSet(b->point.x-a->point.x,b->point.y-a->point.y,b->point.z-a->point.z,0));max_angle=std::max(max_angle,XMConvertToDegrees(acosf(std::clamp(XMVectorGetX(XMVector3Dot(expected,actual)),-1.f,1.f))));}
                auto*l=find_point("LeftFoot"),*r=find_point("RightFoot"),*h=find_point("Hips");auto sl=std::find_if(animation_frame.begin(),animation_frame.end(),[](const auto&j){return j.name=="LeftFoot";}),sr=std::find_if(animation_frame.begin(),animation_frame.end(),[](const auto&j){return j.name=="RightFoot";}),sh=std::find_if(animation_frame.begin(),animation_frame.end(),[](const auto&j){return j.name=="Hips";});
                if(l&&r&&h&&sl!=animation_frame.end()&&sr!=animation_frame.end()&&sh!=animation_frame.end()){auto index=[&](const char*n){return size_t(std::find(rig.names.begin(),rig.names.end(),n)-rig.names.begin());};float ratio=(rest[index("Hips")]._42-base->bind_feet)*base->bind_scale/std::max(10.f,sh->bind._42);float expected=(std::min(rest[index("LeftFoot")]._42,rest[index("RightFoot")]._42)-base->bind_feet)*base->bind_scale+(std::min(sl->animated._42,sr->animated._42)-std::min(sl->bind._42,sr->bind._42))*ratio;max_support_error=std::max(max_support_error,fabsf(std::min(l->point.y,r->point.y)-expected));}
                if(k==0||k==count/3||k==2*count/3||k==count){check(renderer.model(current),"Upload de animacao falhou");Camera cam;cam.target={0,90,0};cam.distance=285;cam.synchronize_orbit();check(renderer.render_inspection(760,820,{cam.position,cam.yaw,cam.pitch,cam.fov},true),"Render FBX falhou");check(save_png(device.Get(),context.Get(),renderer.image(),output/(std::string("sad-idle-")+label+"-"+std::to_string(k)+".png")),"PNG FBX falhou");}
            }
            check(max_error<.15f,"Conversao mudou o comprimento de um osso FIFA");check(max_movement>1,"FBX nao move o modelo FIFA");
            check(max_angle<.15f,"Eixos dos membros nao acompanham a animacao de origem");check(max_support_error<.01f,"Altura do tornozelo de apoio nao acompanha a origem");
            report<<count+1<<" quadros verificados; erro maximo de comprimento: "<<max_error<<" cm; maior movimento: "<<max_movement<<" cm; malha finita OK\n";report<<"Direcao de bracos, antebracos, coxas, pernas e pes: erro maximo "<<max_angle<<" graus; altura normalizada do tornozelo de apoio: erro maximo "<<max_support_error<<" cm\n";
            Settings preset=config;preset.scene=kind?4:3;preset.club=1043;preset.player=player->player_id;preset.pose=kind?201:101;preset.coach_target=kind;preset.joints.clear();preset.actors.clear();preset.objects.clear();preset.keys.clear();preset.mapping=mapping;preset.fbx_file=utf8(fbx.wstring());preset.camera.target={0,90,0};preset.camera.distance=285;preset.camera.synchronize_orbit();save_settings(root/L"presets"/(std::string("sad-idle-")+label+".xml"),preset);
        }
        animation_frame.clear();report<<"PASSOU nos testes estruturais. Verificar visualmente contatos com o chao, torcao e proporcoes; nao implica compatibilidade perfeita com qualquer FBX. Nenhum arquivo do FIFA alterado.\n";return 0;
    }catch(const std::exception&e){animation_frame.clear();report<<"FALHOU: "<<e.what()<<"\n";return 1;}
}
}
